export const koUi: Record<string, string> = {
  "…or any card UID (e.g. an unknown card)": "또는 임의의 카드 UID (미등록 카드)",
  "A building that still has doors cannot be deleted.": "출입문이 있는 건물은 지울 수 없습니다.",
  "A building that still has doors stays in place and the server reports that it is in use.":
    "출입문이 남아 있으면 건물은 그대로 있고, 서버는 사용 중이라고 알립니다.",
  "A debit cannot use money already reserved by open payouts.": "진행 중인 지급에 묶인 돈은 차감할 수 없습니다.",
  "A door uses a building. A till reader uses a serial number and is not tied to a counter.":
    "출입문은 건물을 쓰고, 계산 단말기는 일련번호를 쓰며 매장에 묶이지 않습니다.",
  "A last working day does not change status or release the card. Set status to Terminated when someone leaves. Delete is a soft delete.":
    "마지막 근무일은 상태나 카드를 바꾸지 않습니다. 떠날 때는 상태를 퇴직으로 하십시오. 삭제는 숨김입니다.",
  "A reason is required.": "사유가 필요합니다.",
  "A till or counter where goods are sold. Delete is a soft delete.": "물건을 파는 계산대입니다. 삭제는 숨김입니다.",
  "A user can have several roles. You can only grant roles you are allowed to grant.":
    "사용자는 역할을 여러 개 가질 수 있습니다. 줄 수 있는 역할만 줄 수 있습니다.",
  Action: "동작",
  "Active staff who are not inside any building.": "어느 건물에도 없는 근무중 직원입니다.",
  Add: "추가",
  "Add a missing moment. Choose Out when someone is still counted inside because they never scanned out.":
    "빠진 시각을 넣습니다. 퇴장 스캔이 없어 안에 있는 것으로 남으면 퇴장을 고르십시오.",
  "Add item": "품목 추가",
  "Add money": "돈 넣기",
  "Add record": "기록 추가",
  "Add role": "역할 추가",
  Adjust: "조정",
  After: "이후",
  Amount: "금액",
  "Amount is a decimal, such as 25.00.": "금액은 25.00처럼 소수입니다.",
  Approve: "승인",
  Assign: "배정",
  Assigned: "배정됨",
  Assignment: "배정",
  "Attendance day": "출퇴근 날",
  "Attendance record": "출입 기록",
  "Audit event": "감사 사건",
  Available: "가능",
  "Available balance is the balance minus money reserved by open payouts.":
    "쓸 수 있는 잔액은 잔액에서 진행 중인 지급에 묶인 돈을 뺀 것입니다.",
  Balance: "잔액",
  "Balance after pay ·": "결제 후 잔액 ·",
  Before: "이전",
  Block: "차단",
  "Bookings are final and cannot be refunded.": "예약은 끝나면 되돌릴 수 없습니다.",
  Building: "건물",
  "Cancel draft": "초안 취소",
  "Cancel purchase": "판매 취소",
  Card: "카드",
  "Card ·": "카드 ·",
  "Card scans": "카드 스캔",
  "Cards are retired, not deleted, so scan history stays intact.": "카드는 지우지 않고 폐기하여 스캔 기록이 남습니다.",
  Change: "변경",
  "Clears the spending PIN so the developer can set a new one.": "지출 PIN을 지워 개발자가 새로 정하게 합니다.",
  Close: "닫기",
  "Close a seller later by setting status to Closed.": "판매를 끝낼 때는 상태를 폐점으로 바꿉니다.",
  Closed: "폐점",
  "Code is the short label, such as B1.": "코드는 B1처럼 짧은 표시입니다.",
  Contact: "연락",
  "Correct a balance": "잔액 고치기",
  Correction: "정정",
  "Courts are booked at the desk. The developer taps a card and enters a PIN.":
    "운동장은 창구에서 예약합니다. 개발자가 카드를 대고 PIN을 넣습니다.",
  "Create building": "건물 만들기",
  "Create developer": "개발자 만들기",
  "Create good": "상품 만들기",
  "Create position": "매장 만들기",
  "Create seller": "판매자 만들기",
  Currency: "화폐",
  "Current balance ·": "현재 잔액 ·",
  "Current PIN": "현재 PIN",
  "Daily row": "하루 기록",
  "Daily rows for the signed-in developer.": "로그인한 개발자의 하루 기록입니다.",
  Day: "날",
  "Delete building": "건물 삭제",
  "Delete developer": "개발자 삭제",
  "Delete good": "상품 삭제",
  "Delete position": "매장 삭제",
  "Department ·": "부서 ·",
  "Deposits, purchases, refunds, and adjustments.": "입금, 구매, 환불, 조정입니다.",
  Description: "설명",
  Developer: "개발자",
  "Developer ·": "개발자 ·",
  "Developer balances. Frozen accounts can still receive deposits.": "개발자 잔액입니다. 동결된 계좌도 입금은 됩니다.",
  "Developer paying": "결제하는 개발자",
  "Device request": "단말기 요청",
  Door: "출입문",
  "Door IP": "출입문 IP",
  "Doors and till readers. Online means the device was heard from in the last two minutes.":
    "출입문과 계산 단말기입니다. 접속은 최근 2분 안에 신호를 받은 것입니다.",
  "Doors are registered separately and point at this building.": "출입문은 따로 등록하고 이 건물을 가리킵니다.",
  "Each submission carries its own idempotency key.": "보낼 때마다 새 중복방지 열쇠가 붙습니다.",
  "Email is the sign-in name.": "전자우편이 로그인 이름입니다.",
  "Employee number": "직원번호",
  "Employee number ·": "직원번호 ·",
  "Employee number and full name are required.": "직원번호와 이름은 필수입니다.",
  "Find a test developer": "시험 개발자 찾기",
  "Full name": "이름",
  First: "처음",
  "Four to six digits. Enter the current PIN when you already have one.":
    "숫자 네 자리부터 여섯 자리입니다. 이미 있으면 현재 PIN을 넣으십시오.",
  Freeze: "동결",
  "Give this card to a developer.": "이 카드를 개발자에게 줍니다.",
  Good: "상품",
  Hours: "시간",
  Images: "사진",
  "Inside now": "지금 안에 있음",
  "Issue a new card to the current holder and retire this one.": "지금 가진 사람에게 새 카드를 주고 이 카드는 폐기합니다.",
  "Items sold at a service position. Delete is a soft delete.": "매장에서 파는 품목입니다. 삭제는 숨김입니다.",
  Last: "마지막",
  "Last seen": "마지막 수신",
  "Latest record is an in, and no later out has been recorded.": "마지막 기록이 입장이며 그 뒤 퇴장이 없습니다.",
  "Leave the seller empty when you are creating it for your own seller.": "자기 판매자면 판매자를 비우십시오.",
  "Leaving the company is a status change, not a hard delete.": "회사를 떠나는 것은 상태 변경이며 완전 삭제가 아닙니다.",
  Line: "줄",
  List: "목록",
  "Live totals from the company API. Charts will sit under them.": "회사 API의 현재 합계입니다.",
  Location: "위치",
  "Manual attendance": "수동 출퇴근",
  "Mark paid": "지급 완료",
  "Mark processing": "처리중으로",
  Movement: "이동",
  "Movements on the signed-in developer's wallet.": "로그인한 개발자 지갑의 이동입니다.",
  "My attendance": "내 출퇴근",
  "My attendance records": "내 출입 기록",
  "My developer profile": "내 개발자 신상",
  "My profile": "내 신상",
  "My purchases": "내 구매",
  "My seller": "내 판매",
  "My seller balance": "내 판매 잔액",
  "My seller profile": "내 판매자 신상",
  "My transactions": "내 거래",
  "My wallet": "내 지갑",
  "Name is required.": "이름은 필수입니다.",
  "New building": "건물 추가",
  "New card": "카드 추가",
  "New good": "상품 추가",
  "New position": "매장 추가",
  "New seller": "판매자 추가",
  "New service position": "매장 추가",
  "Newest card scans first.": "최근 카드 스캔이 먼저입니다.",
  "No assignments yet.": "배정이 없습니다.",
  "No attendance for this account.": "이 계정의 출퇴근이 없습니다.",
  "No audit events yet.": "감사 기록이 없습니다.",
  "No bookings yet.": "예약이 없습니다.",
  "No buildings yet.": "건물이 없습니다.",
  "No cards yet.": "카드가 없습니다.",
  "No devices yet.": "단말기가 없습니다.",
  "No goods yet.": "상품이 없습니다.",
  "No images.": "사진이 없습니다.",
  "No items yet.": "품목이 없습니다.",
  "No matching developers": "맞는 개발자가 없습니다",
  "No movements yet.": "이동이 없습니다.",
  "No numbers for this chart.": "이 도표에 숫자가 없습니다.",
  "No payouts yet.": "지급이 없습니다.",
  "No positions yet.": "매장이 없습니다.",
  "No purchases for this account.": "이 계정의 구매가 없습니다.",
  "No records for this account.": "이 계정의 기록이 없습니다.",
  "No rentals are bookable.": "예약할 대여가 없습니다.",
  "No roles.": "역할이 없습니다.",
  "No scans yet.": "스캔이 없습니다.",
  "No seller accounts yet.": "판매 계정이 없습니다.",
  "No seller transactions yet.": "판매 거래가 없습니다.",
  "No sellers yet.": "판매자가 없습니다.",
  "No transactions for this account.": "이 계정의 거래가 없습니다.",
  "No transactions yet.": "거래가 없습니다.",
  "No wallets yet.": "지갑이 없습니다.",
  "Present in any building.": "어느 건물이든 안에 있습니다.",
  "Present in this building.": "이 건물 안에 있습니다.",
  "Nobody is in.": "안에 있는 사람이 없습니다.",
  "Nobody is inside this selection.": "이 선택 안에 사람이 없습니다.",
  "Nobody is out.": "밖에 있는 사람이 없습니다.",
  None: "없음",
  "Nothing to summarize yet": "아직 요약할 내용이 없습니다",
  "Only a zero balance can be closed.": "잔액이 0일 때만 닫을 수 있습니다.",
  "Open draft": "초안 열기",
  "Optional: the transfer has started.": "선택: 이체가 시작되었습니다.",
  "Other court id": "다른 운동장 번호",
  "Leave empty to keep this court": "이 운동장을 유지하려면 비우십시오",
  Pay: "지급",
  Payout: "지급",
  Permissions: "권한",
  "Permission sets": "권한 묶음",
  "Pick a free stretch on the slot grid. The developer taps their card on the desk reader, then enters their PIN.":
    "빈 구간을 고르십시오. 개발자가 창구 단말기에 카드를 대고 PIN을 넣습니다.",
  PIN: "PIN",
  "Positive amounts credit the wallet. Negative amounts debit it.": "양수는 지갑에 넣고 음수는 뺍니다.",
  "Positive credits the seller. Negative debits them. A reason is required.": "양수는 판매자에게 넣고 음수는 뺍니다. 사유가 필요합니다.",
  "Post adjustment": "조정 올리기",
  "Post deposit": "입금 올리기",
  Price: "가격",
  "Price is a decimal and must be above 0 for a rental. The service position decides who sells it.":
    "가격은 소수이며 대여는 0보다 커야 합니다. 어느 매장이 파는지가 정해집니다.",
  Purchase: "판매",
  "Purchases charged to the signed-in developer.": "로그인한 개발자에게 청구된 구매입니다.",
  Qty: "수량",
  Quantity: "수량",
  "Readers send scans with their own key, not a user session.": "단말기는 사용자 세션이 아니라 자기 열쇠로 스캔을 보냅니다.",
  Record: "기록",
  "Record stock change": "재고 기록",
  "Records are voided later, not deleted.": "기록은 지우지 않고 나중에 무효로 합니다.",
  "Records that the money was handed over and debits the seller.": "돈을 건넨 것으로 기록하고 판매자 잔액을 뺍니다.",
  Reference: "참조",
  "Register card": "카드 등록",
  Reject: "거절",
  "Reject scans while the card stays assigned.": "카드가 배정된 채로 스캔을 거절합니다.",
  Remove: "빼기",
  "Remove image": "사진 빼기",
  Rental: "대여",
  Reopen: "다시 열기",
  Replace: "바꾸기",
  Request: "요청",
  "Requested, approved, paid, rejected, or cancelled.": "요청, 승인, 지급, 거절, 취소입니다.",
  Reserved: "보류",
  "Reset PIN": "PIN 초기화",
  "Restock adds quantity. Damage subtracts it. Adjustment sets the counted quantity.":
    "입고는 수량을 더하고, 손망실은 빼며, 조정은 센 수량으로 맞춥니다.",
  Retire: "폐기",
  Returned: "반납",
  "RFID cards and who holds them.": "RFID 카드와 가진 사람입니다.",
  Role: "역할",
  "Roles are assigned on a user. They are not deleted here.": "역할은 사용자에게 줍니다. 여기서는 지우지 않습니다.",
  "Rotate key": "열쇠 바꾸기",
  Rules: "규칙",
  "Sales, payouts, and signed adjustments.": "판매, 지급, 서명된 조정입니다.",
  "Save PIN": "PIN 저장",
  "Scans and manual corrections for the signed-in developer.": "로그인한 개발자의 스캔과 수동 수정입니다.",
  "Seller adjustment": "판매자 조정",
  "Seller balance": "판매 잔액",
  "Seller balances": "판매 잔액",
  "Seller transaction": "판매 거래",
  "Seller transactions": "판매 거래",
  "Sellers are closed with a status change, not deleted.": "판매자는 지우지 않고 상태로 닫습니다.",
  "Sellers manage their own positions. Managers can manage all of them.": "판매자는 자기 매장을 다루고, 관리자는 모두 다룹니다.",
  "Send scan": "스캔 보내기",
  "Service position": "매장",
  "Service positions": "매장",
  "Set status to Closed when the seller stops trading.": "판매를 멈추면 상태를 폐점으로 하십시오.",
  Settings: "설정",
  "Show slots": "시간 보기",
  "Simulate tap (testing only)": "카드 대기 시험 (시험만)",
  Since: "이후",
  Sites: "장소",
  SKU: "SKU",
  Slot: "칸",
  "Soft-deletes this good.": "이 상품을 목록에서 숨깁니다.",
  "Soft-deletes this person. Prefer Terminated when they are leaving the company.":
    "이 사람을 목록에서 숨깁니다. 회사를 떠나면 퇴직을 쓰십시오.",
  "Soft-deletes this position.": "이 매장을 목록에서 숨깁니다.",
  "Spending PIN": "지출 PIN",
  "Spending stops. Deposits still work.": "지출은 멈추고 입금은 됩니다.",
  Stock: "재고",
  "Stock changes after creation go through the stock action.": "만든 뒤의 재고는 재고 동작으로 바꿉니다.",
  "Stock changes recorded against goods.": "상품에 기록된 재고 변경입니다.",
  "Submit scan": "스캔 제출",
  "Tables and filters for this section will sit here.": "이 구역의 표와 거름이 여기 있습니다.",
  "Take an unassigned card out of circulation.": "배정되지 않은 카드를 사용에서 뺍니다.",
  "Take the card back. The history stays.": "카드를 돌려받습니다. 기록은 남습니다.",
  "The amount cannot exceed the available balance. Leave the seller empty to use your own seller.":
    "금액은 쓸 수 있는 잔액을 넘을 수 없습니다. 자기 판매자면 판매자를 비우십시오.",
  "The code must match the ID the hardware sends, such as Door1 or Reader2.":
    "코드는 장치가 보내는 ID와 같아야 합니다. Door1, Reader2처럼.",
  "The old key stops working immediately. Copy the new key before you leave. You will not see it again.":
    "옛 열쇠는 즉시 멈춥니다. 떠나기 전에 새 열쇠를 복사하십시오. 다시 보이지 않습니다.",
  "The password rules are checked by the server.": "비밀번호 규칙은 서버가 확인합니다.",
  "The person signed in on this browser.": "이 브라우저에 로그인한 사람입니다.",
  "The requester cannot approve their own payout.": "요청한 사람은 자기 지급을 승인할 수 없습니다.",
  "The row stays in history with this reason.": "이 사유와 함께 기록에 남습니다.",
  "The same client event id is accepted once. A repeat returns the original result.":
    "같은 단말기 사건 번호는 한 번만 받습니다. 반복은 처음 결과를 돌려줍니다.",
  "The service position owns the goods that can be added. The reader is found from this computer's address.":
    "매장이 넣을 수 있는 상품을 가집니다. 단말기는 이 컴퓨터 주소로 찾습니다.",
  "The till reader is the one plugged into this PC. The page never sends a card number.":
    "계산 단말기는 이 PC에 꽂힌 것입니다. 이 쪽은 카드 번호를 보내지 않습니다.",
  "The UID is printed on the card and sent by readers.": "UID는 카드에 찍혀 있고 단말기가 보냅니다.",
  "There is no delete. Clear Active later to turn a device off. Registration still shows an API key once, even for a door that uses a fixed IP.":
    "삭제는 없습니다. 나중에 근무중을 끄면 장치가 꺼집니다. 등록 때 API 열쇠는 한 번 보이며, 고정 IP 출입문도 그렇습니다.",
  "These use the signed-in account. The server returns an error if you have no matching profile.":
    "로그인한 계정을 씁니다. 맞는 신상이 없으면 서버가 오류를 줍니다.",
  "This account has no company-wide lists.": "이 계정에는 회사 전체 목록이 없습니다.",
  "This payment cannot be undone.": "이 결제는 되돌릴 수 없습니다.",
  Till: "계산",
  "To pay ·": "낼 금액 ·",
  "Toggle Sidebar": "옆줄 접기",
  Transaction: "거래",
  Unassign: "배정 해제",
  Unblock: "차단 해제",
  Unfreeze: "동결 해제",
  Until: "까지",
  "Until it starts, move this booking to another time or another court of the same seller. The new time must cost the same. No card tap.":
    "시작 전까지 같은 판매자의 다른 시간이나 다른 운동장으로 옮깁니다. 새 시간은 같은 금액이어야 합니다. 카드는 필요 없습니다.",
  "Update password": "비밀번호 바꾸기",
  "Update qty": "수량 고치기",
  "Upload image": "사진 올리기",
  "Use this reader": "이 단말기 사용",
  User: "사용자",
  "Void record": "기록 무효",
  Wallet: "지갑",
  "Wallet transactions": "지갑 거래",
  What: "내용",
  Who: "누구",
  "Who changed what, with the previous and next values.": "누가 무엇을 바꿨는지, 이전 값과 다음 값입니다.",
  "Who held which card, including returned and replaced cards.": "누가 어느 카드를 가졌는지, 반납과 교체도 있습니다.",
  "Withdraw a request that has not been approved.": "아직 승인되지 않은 요청을 거둡니다.",
  "You cannot approve a payout you requested.": "자신이 요청한 지급은 승인할 수 없습니다.",
  "Your account cannot add attendance records.": "이 계정은 출입 기록을 넣을 수 없습니다.",
  "Your account cannot adjust balances.": "이 계정은 잔액을 조정할 수 없습니다.",
  "Your account cannot adjust seller balances.": "이 계정은 판매 잔액을 조정할 수 없습니다.",
  "Your account cannot create buildings.": "이 계정은 건물을 만들 수 없습니다.",
  "Your account cannot create developers.": "이 계정은 개발자를 만들 수 없습니다.",
  "Your account cannot create goods.": "이 계정은 상품을 만들 수 없습니다.",
  "Your account cannot create sellers.": "이 계정은 판매자를 만들 수 없습니다.",
  "Your account cannot create service positions.": "이 계정은 매장을 만들 수 없습니다.",
  "Your account cannot create users.": "이 계정은 사용자를 만들 수 없습니다.",
  "Your account cannot open a till draft.": "이 계정은 계산 초안을 열 수 없습니다.",
  "Your account cannot open buildings.": "이 계정은 건물을 열 수 없습니다.",
  "Your account cannot open this section.": "이 계정은 이 구역을 열 수 없습니다.",
  "Your account cannot post deposits.": "이 계정은 입금을 올릴 수 없습니다.",
  "Your account cannot register cards.": "이 계정은 카드를 등록할 수 없습니다.",
  "Your account cannot register devices.": "이 계정은 단말기를 등록할 수 없습니다.",
  "Your account cannot submit reader scans.": "이 계정은 단말기 스캔을 보낼 수 없습니다.",
  "Your own developer profile.": "자신의 개발자 신상입니다.",
  "Your own seller profile.": "자신의 판매자 신상입니다.",
  "Your records": "자신의 기록",
  "New PIN": "새 PIN",
  "Old password": "현재 비밀번호",
  "New password": "새 비밀번호",
  "Max slots per booking": "한 번에 최대 칸",
  "Max slots per person per day": "하루 한 사람 최대 칸",
  "Max days ahead": "미리 예약 일수",
  "Slot minutes": "칸 분",
  "Opening time": "여는 시각",
  "Closing time": "닫는 시각",
  Opens: "여는 시각",
  Closes: "닫는 시각",
  "Book ahead": "미리 예약",
  Recognized: "확인됨",
  "Not available for this account": "이 계정에서는 볼 수 없습니다",
  "this developer": "이 개발자",
  "Hold the card on the reader. This closes when the card is recognized.":
    "단말기에 카드를 대십시오. 카드가 확인되면 이 창이 닫힙니다.",
  "Current password": "현재 비밀번호",
  "People on file": "등록된 사람",
  "RFID cards": "RFID 카드",
  "Registered readers": "등록된 단말기",
  "Accounts that can sign in": "로그인할 수 있는 계정",
  "Attendance days": "출퇴근 날",
  "Stored daily rows": "저장된 하루 기록",
  "Audit events": "감사 사건",
  "Recorded changes": "기록된 변경",
  "Developer balances": "개발자 잔액",
  "Items for sale": "판매 품목",
  "Till orders": "계산 주문",
  "Sellers on file": "등록된 판매자",
  "No previous sign-in": "이전 로그인 없음",
  "No chart data yet": "아직 도표 자료가 없습니다",
  "This area is reserved for a chart.": "도표가 들어올 자리입니다.",
  "Daily presence will be charted here.": "하루 재실이 여기 도표로 나옵니다.",
  "Scan results over time will be charted here.": "시간의 스캔 결과가 여기 도표로 나옵니다.",
  "Directory, status, and each person's card and attendance.": "명부, 상태, 그리고 각 사람의 카드와 출퇴근입니다.",
  "RFID cards, assignments, and block or retire actions.": "RFID 카드, 배정, 차단과 폐기입니다.",
  "Door readers and the one-time API key when a reader is created or rotated.": "출입 단말기와, 만들거나 열쇠를 바꿀 때 한 번 보이는 API 열쇠입니다.",
  "Recent card scans, including unknown cards that can be registered.": "최근 카드 스캔이며, 등록할 수 있는 미등록 카드도 있습니다.",
  "Daily attendance and manual corrections.": "하루 출퇴근과 수동 수정입니다.",
  "Accounts, roles, and who can sign in.": "계정, 역할, 그리고 누가 로그인할 수 있는지입니다.",
  "What changed, who changed it, and the previous and next values.": "무엇이 바뀌었는지, 누가 바꿨는지, 이전 값과 다음 값입니다.",
  "Attendance door": "출입문",
  "Till reader": "계산 단말기",
  "Code (the ID the hardware sends)": "코드 (장치가 보내는 ID)",
  "Allowed door IP": "출입문 허용 IP",
  "Allowed IP": "허용 IP",
  Both: "둘 다",
  Purpose: "용도",
  "Serial number": "일련번호",
  "A door needs a building. It can sign in from a fixed IP, or with the API key shown once after you save.":
    "출입문에는 건물이 필요합니다. 고정 IP로 로그인하거나, 저장 후 한 번 보이는 API 열쇠로 로그인합니다.",
  "A till reader is not tied to a counter. It needs the serial number on the device and signs in with that serial number and its code.":
    "계산 단말기는 매장에 묶이지 않습니다. 장치의 일련번호가 필요하며 그 번호와 코드로 로그인합니다.",
  Kind: "종류",
  Actor: "실행한 사람",
  "Alt text": "그림 설명",
  Approved: "승인됨",
  "Assigned by": "배정한 사람",
  "Balance after": "이후 잔액",
  Birthday: "생일",
  Cancelled: "취소됨",
  "Card UID": "카드 UID",
  Chart: "도표",
  "Client event": "단말기 사건",
  "Client event id": "단말기 사건 번호",
  Confirmed: "확인됨",
  "Contact name": "연락 이름",
  "Counted adjustment": "실사 조정",
  "Counted quantity": "센 수량",
  Created: "만든 때",
  Damage: "손망실",
  "Device code": "단말기 코드",
  Direction: "방향",
  "End reason": "끝 사유",
  "Event time": "사건 시각",
  "Home address": "집 주소",
  Image: "사진",
  "Initial quantity": "처음 수량",
  "Last IP": "마지막 IP",
  "Last working day": "마지막 근무일",
  "Linked user": "연결된 사용자",
  "Max slots per day": "하루 최대 칸",
  "New label": "새 표시",
  "New UID": "새 UID",
  Notes: "비고",
  Paid: "지급됨",
  "Payment reference": "지급 참조",
  "PIN locked until": "PIN 잠김 시각",
  Processing: "처리중",
  Product: "물건",
  "Quantity after": "이후 수량",
  "Reader key": "단말기 열쇠",
  Received: "받은 시각",
  Records: "기록",
  Rejected: "거절됨",
  "Rejection reason": "거절 사유",
  "Rental closes": "대여 닫는 시각",
  "Rental opens": "대여 여는 시각",
  "Rental slot minutes": "대여 칸 분",
  Requested: "요청됨",
  Restock: "입고",
  "Returned by": "반납한 사람",
  Service: "서비스",
  "Start date": "시작일",
  "Track stock": "재고 추적",
  "User agent": "사용자 프로그램",
  Version: "판",
  "Voided at": "무효 시각",
  "Worked seconds": "근무 초",
  "Store login (SELLER role)": "매장 로그인 (SELLER 역할)",
  "Store login": "매장 로그인",
  "No login": "로그인 없음",
  "No store login yet": "아직 매장 로그인이 없습니다",
  "Position manager (SELLER role)": "매대 책임자 (SELLER 역할)",
  "No manager": "책임자 없음",
  Owners: "소유자",
  Managers: "관리자",
  "Company statistics": "회사 통계",
  "Your account cannot open company statistics.": "이 계정은 회사 통계를 열 수 없습니다.",
  "Could not load company statistics.": "회사 통계를 불러올 수 없습니다.",
  "Not terminated": "퇴직은 빠집니다",
  "Present right now": "지금 안에 있음",
  "Till sales and bookings": "계산 판매와 예약",
  "People present each day.": "날마다 나온 사람입니다.",
  "Deposits and spending each day.": "날마다 입금과 지출입니다.",
  Deposits: "입금",
  Spending: "지출",
  "Store sales": "매장 판매",
  "Money held": "가진 금액",
};
