export const koUi: Record<string, string> = {
  "The card used at the doors and tills.": "출입문과 판매대에서 쓰는 카드입니다.",
  "Replace with a new card": "새 카드로 바꾸기",
  "No card. Your account can't assign cards.": "카드가 없습니다. 이 계정은 카드를 배정할수 없습니다.",
  "No card yet. Tap one on the card assign reader to assign it.": "아직 카드가 없습니다. 카드 배정 발급기에 카드를 대여 배정하십시오.",
  "Tap the new card. The old one is retired; the PIN stays.": "새 카드를 대십시오. 이전 카드는 페기되고 PIN은 그대로 남습니다.",
  "This card can't be used. Tap another card.": "이 카드는 쓸수 없습니다. 다른 카드를 대십시오.",
  "This card can't be assigned. Tap another card.": "이 카드는 배정할수 없습니다. 다른 카드를 대십시오.",
  "Lost, broken, …": "분실, 파손, …",
  "Replace card": "카드 바꾸기",
  "Tap a card on the card assign reader first.": "먼저 카드 배정 발급기에 카드를 대십시오.",
  "Tap the new card on the card assign reader first.": "먼저 카드 배정 발급기에 새 카드를 대십시오.",
  "Hides this person (soft delete); their history stays. Prefer Terminated when they are leaving the company.": "이 사람을 숨깁니다(기록은 남음). 회사를 떠날 때는 퇴직으로 하십시오.",
  "Search, or type a new one": "검색하거나 새로 입력",
  "None yet: type a new one.": "아직 없습니다: 새로 입력하십시오.",
  "Clear": "지우기",
  "Choose or add a department": "부서 선택 또는 추가",
  "RFID card": "RFID 카드",
  "Assign a card later on the Assign card page.": "카드는 후에 카드 배정 페지에서 배정하십시오.",
  "Optional: tap the new developer's card on the card assign reader. They type a purchase PIN twice.": "선택: 새 개발자의 카드를 카드 배정 발급기에 대십시오. 개발자가 구매 PIN을 두번 입력합니다.",
  "No card assign reader is registered (Readers → New device → Card assign reader).": "등록된 카드 배정 발급기가 없습니다(인식기 → 새 장치 → 카드 배정 발급기).",
  "This card can't be assigned. Tap another card, or leave it for later.": "이 카드는 배정할수 없습니다. 다른 카드를 대거나 후에 하십시오.",
  "Don't assign a card now": "지금 카드를 배정하지 않기",
  "Create developer and assign card": "개발자를 만들고 카드 배정",
  "New store": "새 매장",
  "The store, its login, its first counter and its till reader, saved together in one step.": "매장, 가입 계정, 첫 판매대, 판매대 인식기를 한번에 보관합니다.",
  "Store": "매장",
  "The counter is named after the store unless you name it. More counters and readers can be added on the store's page later.": "판매대 이름을 넣지 않으면 매장 이름을 씁니다. 판매대와 인식기는 후에 매장 페지에서 더 추가할수 있습니다.",
  "Create store": "매장 만들기",
  "Store name": "매장 이름",
  "Create a new login": "새 가입 계정 만들기",
  "Use an existing seller login": "있는 판매자 계정 쓰기",
  "No login yet": "아직 계정 없음",
  "Seller login": "판매자 계정",
  "First counter": "첫 판매대",
  "Same as the store name": "매장 이름과 같게",
  "None for now": "지금은 없음",
  "No unassigned till reader": "배정되지 않은 판매대 인식기 없음",
  "Your account cannot create stores.": "이 계정은 매장을 만들수 없습니다.",
  "The card readers at this store's tills. Only this store's purchases use them.": "이 매장 판매대의 카드 인식기입니다. 이 매장의 판매만 씁니다.",
  "No till reader assigned yet.": "아직 배정된 판매대 인식기가 없습니다.",
  "Assign a till reader": "판매대 인식기 배정",
  "Every till reader is assigned. Register a new one under Readers → New device.": "모든 판매대 인식기가 배정되였습니다. 인식기 → 새 장치에서 새로 등록하십시오.",
  "Assigned to": "배정",
  "Not assigned: no seller uses this reader yet.": "배정 안됨: 아직 이 인식기를 쓰는 판매자가 없습니다.",
  "Save assignment": "배정 보관",
  "Choose a till reader.": "판매대 인식기를 선택하십시오.",
  "Register the till reader here, then assign it to a seller (on the reader's page, the seller's page or New store). Only that seller's purchases use it. It is recognised by its ID alone. Each ID can be used once.": "판매대 인식기를 여기서 등록한 다음 판매자에게 배정하십시오(인식기 페지, 판매자 페지 또는 새 매장에서). 그 판매자의 판매만 씁니다. ID만으로 알아보며 ID마다 한번만 쓸수 있습니다.",
  "Developers by deposits": "입금별 개발자",
  "Developers with deposits or spending in the period. Balance is now.": "기간에 입금이나 지출이 있은 개발자입니다. 잔고는 현재 잔고입니다.",
  "By deposit total": "입금 합계순",
  "By deposit count": "입금 횟수순",
  "No deposits or spending in this period.": "이 기간에 입금이나 지출이 없습니다.",
  "Deposit count": "입금 횟수",
  "Delete for good": "영구 삭제",
  "Counting its history…": "기록을 세는중…",
  "Deleted with it": "함께 삭제되는것",
  "No history: only the record itself.": "기록이 없습니다: 이 항목만 삭제됩니다.",
  "Stays": "남는것",
  "This can't be undone here. A database backup is made first (restore it on the Backups page if needed).": "여기서는 되돌릴수 없습니다. 먼저 자료기지를 예비복사합니다(필요하면 예비복사 페지에서 복구하십시오).",
  "Deleting…": "삭제하는중…",
  "Money transactions": "돈 거래",
  "TCP log entries": "TCP 기록",
  "Their login (user account)": "가입 계정",
  "Purchases made with it (kept without it)": "이것으로 한 판매(이것 없이 남음)",
  "Developers' money transactions for these purchases": "이 판매에 대한 개발자들의 돈 거래",
  "Till readers (kept, no longer assigned)": "판매대 인식기(남지만 배정 해제)",
  "What this user did (kept under their name)": "이 사용자가 한 작업(이름으로 남음)",
  "Developer profile (kept, no longer linked)": "개발자 정보(남지만 련결 해제)",
  "Seller profile (kept, no longer linked)": "판매자 정보(남지만 련결 해제)",
  "Deletes this person and everything recorded about them: scans, attendance, money and purchases. Their login and card stay.": "이 사람과 그에 대한 모든 기록(인식, 출퇴근, 돈, 판매)을 삭제합니다. 가입 계정과 카드는 남습니다.",
  "Deletes the card, its scans and the attendance made from them. Purchases paid with it stay.": "카드와 그 인식, 그로부터 만든 출퇴근 기록을 삭제합니다. 그 카드로 한 판매는 남습니다.",
  "Deletes the reader, its scans, the attendance made from them and its TCP log. Purchases through it stay.": "인식기와 그 인식, 그로부터 만든 출퇴근 기록, TCP 기록을 삭제합니다. 그 인식기로 한 판매는 남습니다.",
  "Deletes the seller with its service positions, goods, stock history, purchases and bookings. Developers' money stays as it is.": "판매자와 그 매장, 상품, 재고 기록, 판매, 예약을 삭제합니다. 개발자들의 돈은 그대로 남습니다.",
  "Deletes the service position with its goods, stock history, purchases and bookings.": "매장과 그 상품, 재고 기록, 판매, 예약을 삭제합니다.",
  "Deletes the good, its stock history and the purchases that include it.": "상품과 그 재고 기록, 그 상품이 들어간 판매를 삭제합니다.",
  "The system is offline while it runs (usually one to a few minutes): doors and tills don't answer.": "진행하는 동안 체계가 멈춥니다(보통 1분에서 몇분): 출입문과 판매대는 응답하지 않습니다.",
  "Restore": "복구",
  "All current data is replaced by this backup. The current data is backed up first and kept, so this can be undone.": "현재 자료가 모두 이 예비복사로 바뀝니다. 현재 자료는 먼저 예비복사하고 보관하므로 되돌릴수 있습니다.",
  "Starting…": "시작하는중…",
  "Restore this backup": "이 예비복사로 복구",
  "Choose a backup file (.dump).": "예비복사 파일(.dump)을 선택하십시오.",
  "Uploaded as": "올린 파일 이름:",
  "The file is too large.": "파일이 너무 큽니다.",
  "The upload failed.": "올리기에 실패했습니다.",
  "Uploading…": "올리는중…",
  "Upload": "올리기",
  "Delete this copy? The restore can then no longer be undone.": "이 사본을 삭제하겠습니까? 그러면 복구를 되돌릴수 없습니다.",
  "A restore is running": "복구가 진행중입니다",
  "The backup was restored": "예비복사로 복구했습니다",
  "The restore failed": "복구에 실패했습니다",
  "The data from before the restore is kept as": "복구전 자료는 다음 이름으로 보관되여 있습니다:",
  "Uploaded": "올린 파일",
  "Upload a backup file": "예비복사 파일 올리기",
  "A .dump made by this system (e.g. a copy on a USB stick, or from another server). It is checked, added to the list above and can then be restored.": "이 체계가 만든 .dump 파일입니다(례: USB에 보관한 사본, 다른 봉사기의 파일). 검사한 다음 우의 목록에 추가되며 복구할수 있습니다.",
  "Restore puts a backup back as the live data. First the current data is backed up, then the file is checked by a trial restore; only then is the live data replaced. The data from before is kept as a separate database: delete it once the restored data is fine.": "복구는 예비복사를 현재 자료로 되돌립니다. 먼저 현재 자료를 예비복사하고, 시험 복구로 파일을 검사한 다음에야 현재 자료를 바꿉니다. 이전 자료는 별도의 자료기지로 보관되므로 복구한 자료가 괜찮으면 삭제하십시오.",
  "No kept databases.": "보관된 자료기지가 없습니다.",
  "Last restore log": "마지막 복구 기록",
  "Restoring the backup…": "예비복사로 복구하는중…",
  "The current data is backed up first, then the backup is checked and put back. The system is offline meanwhile (usually one to a few minutes): doors and tills don't answer.": "먼저 현재 자료를 예비복사한 다음 예비복사를 검사하고 되돌립니다. 그동안 체계는 멈춥니다(보통 1분에서 몇분): 출입문과 판매대는 응답하지 않습니다.",
  "Waiting": "기다리는 시간",
  "The backup of the current data failed, so nothing was restored.": "현재 자료의 예비복사가 실패하여 아무것도 복구하지 않았습니다.",
  "The backup file didn't pass its check, so nothing was changed.": "예비복사 파일이 검사를 통과하지 못하여 아무것도 바꾸지 않았습니다.",
  "Restored, but the data doesn't fit this version (migration failed).": "복구했지만 자료가 이 판본에 맞지 않습니다(이전 실패).",
  "The backup file is gone.": "예비복사 파일이 없습니다.",
  "Backups": "예비복사",
  "Only admins can manage backups.": "관리자만 예비복사를 관리할수 있습니다.",
  "Could not load the backups.": "예비복사 정보를 불러올수 없습니다.",
  "The database is backed up every night and checked by restoring it. Every change is also kept continuously, for restoring to a point in time.": "자료기지는 매일 밤 예비복사하고 복구해보아 검사합니다. 모든 변경도 계속 보관하여 원하는 시점으로 복구할수 있습니다.",
  "Back up now": "지금 예비복사",
  "Backing up…": "예비복사하는중…",
  "The backup has started. This page updates when it has finished.": "예비복사를 시작했습니다. 끝나면 이 페지가 갱신됩니다.",
  "Backups are working": "예비복사가 정상입니다",
  "Backups need attention": "예비복사를 확인해야 합니다",
  "Error": "오유",
  "Last backup": "마지막 예비복사",
  "Running now…": "진행중…",
  "Succeeded": "성공",
  "Failed": "실패",
  "Restore check": "복구 검사",
  "Passed": "통과",
  "The last backup was restored into a scratch database and checked.": "마지막 예비복사를 림시 자료기지에 복구하여 검사했습니다.",
  "Next backup": "다음 예비복사",
  "Every night at": "매일 밤",
  "Off-site copy": "외부 복사",
  "Not set": "설정 안됨",
  "Backups are only on this server's disk.": "예비복사가 이 봉사기의 디스크에만 있습니다.",
  "Backup files": "예비복사 파일",
  "Nightly database backups, newest first. A downloaded file holds personal data and PIN hashes: keep it safe.": "매일 밤의 자료기지 예비복사입니다(최신순). 내려받은 파일에는 개인정보와 PIN 해시가 있으므로 안전하게 보관하십시오.",
  "No backups yet.": "아직 예비복사가 없습니다.",
  "Made": "만든 시간",
  "File": "파일",
  "Size": "크기",
  "Download": "내려받기",
  "Point-in-time base backups": "시점 복구용 기본 예비복사",
  "last": "마지막",
  "next": "다음",
  "Off-site: a mounted folder (second disk, USB disk, NAS) or another server over rsync, not both. Leave both empty for none.": "외부 복사: 련결된 폴더(두번째 디스크, USB 디스크, NAS) 또는 rsync로 다른 봉사기, 둘중 하나만. 둘 다 비우면 하지 않습니다.",
  "Nightly backup time (HH:MM)": "매일 밤 예비복사 시간 (시:분)",
  "Keep nightly backups (days)": "매일 예비복사 보관 (일)",
  "Keep point-in-time base backups (weeks)": "기본 예비복사 보관 (주)",
  "Off-site folder": "외부 폴더",
  "Off-site server (rsync)": "외부 봉사기 (rsync)",
  "Last run": "마지막 실행",
  "Restoring": "복구",
  "Restoring replaces all current data, so it is done on the server, not here. Follow docs/BACKUP_AND_RESTORE.md; for example, with a nightly file:": "복구는 현재 자료를 모두 바꾸므로 여기가 아니라 봉사기에서 합니다. docs/BACKUP_AND_RESTORE.md를 따르십시오. 례를 들어 매일 밤 파일로:",
  "no backup status yet (has the nightly backup ever run?)": "아직 예비복사 상태가 없습니다 (매일 밤 예비복사가 실행된적이 있습니까?)",
  "last database dump is missing or too old": "마지막 자료기지 예비복사가 없거나 너무 오래되였습니다",
  "last dump failed its restore check": "마지막 예비복사가 복구 검사에서 실패했습니다",
  "base backup for point-in-time recovery is missing or too old": "시점 복구용 기본 예비복사가 없거나 너무 오래되였습니다",
  "backups are only on this server's disk (no off-site copy configured)": "예비복사가 이 봉사기의 디스크에만 있습니다 (외부 복사 설정 안됨)",
  "WAL archiving is off (no point-in-time recovery)": "WAL 보관이 꺼져 있습니다 (시점 복구 불가)",
  "WAL archiving is failing": "WAL 보관이 실패하고 있습니다",
  "could not read archiver status": "보관 상태를 읽을수 없습니다",
  "Excel": "Excel",
  "Import and export": "가져오기와 내보내기",
  Added: "추가",
  "Excel import and export": "Excel 가져오기와 내보내기",
  "Download data as Excel files, or add many developers, cards or balances at once from a file.": "자료를 Excel 파일로 내려받거나, 파일로 여러 개발자, 카드, 잔고를 한번에 넣습니다.",
  "Export": "내보내기",
  "Import": "가져오기",
  "Developers and cards": "개발자와 카드",
  "Every developer with their current card. Same columns as the import: edit the file and import it back.": "모든 개발자와 현재 카드입니다. 가져오기와 같은 렬이므로 파일을 고쳐서 다시 가져올수 있습니다.",
  "Developer balances now, and the transactions and purchases of the period.": "현재 개발자 잔고와 기간의 거래, 판매입니다.",
  "Goods and stock": "상품과 재고",
  "Goods with price and stock now, and the stock movements of the period.": "상품의 가격과 현재 재고, 기간의 재고 이동입니다.",
  "New employee numbers are added; existing ones are updated. On an update, an empty cell leaves that field as it is. Building: its code or name.": "새 직원번호는 추가하고 있는 번호는 갱신합니다. 갱신할 때 빈 칸은 그대로 둡니다. 건물: 코드나 이름.",
  "New card UIDs are registered and labels updated. With an employee number, the card is assigned to that developer.": "새 카드 UID는 등록하고 카드번호는 갱신합니다. 직원번호가 있으면 그 개발자에게 카드를 배정합니다.",
  "Opening balances": "초기 잔고",
  "One deposit per row. The same employee, amount and description is deposited only once, so importing a file again adds nothing.": "한 행에 한번 입금합니다. 같은 직원, 금액, 설명은 한번만 입금하므로 파일을 다시 가져와도 더해지지 않습니다.",
  "Download .xlsx": ".xlsx 내려받기",
  "Download template": "양식 내려받기",
  "Start from the template. Check first: nothing is saved, and every problem is listed with its row. Import saves all rows, or none if any row has a problem.": "양식에서 시작하십시오. 먼저 검사하면 아무것도 보관하지 않고 문제마다 행을 보여줍니다. 가져오기는 모든 행을 보관하거나, 문제가 있는 행이 하나라도 있으면 아무것도 보관하지 않습니다.",
  "Check": "검사",
  "Working…": "처리중…",
  "Choose an Excel file (.xlsx).": "Excel 파일(.xlsx)을 선택하십시오.",
  "Nothing was saved. Fix these rows and try again:": "아무것도 보관하지 않았습니다. 이 행들을 고치고 다시 하십시오:",
  "Imported.": "가져왔습니다.",
  "Check passed. Nothing is saved yet: press Import.": "검사를 통과했습니다. 아직 보관하지 않았습니다. 가져오기를 누르십시오.",
  "Rows": "행",
  "Changed": "변경",
  "Unchanged": "변경 없음",
  "Row": "행",
  "Column": "렬",
  "Problem": "문제",
  "Your account cannot import or export data.": "이 계정은 자료를 가져오거나 내보낼수 없습니다.",
  "Account transactions": "계정 거래",
  "Attendance records": "출퇴근 기록",
  "Audit log": "활동기록",
  "Back up and delete all data": "예비복사하고 모든 자료 삭제",
  "Backing up and deleting…": "예비복사하고 삭제하는중…",
  "Backup made before the reset (restore it to undo):": "초기화전에 만든 예비복사 (되돌리려면 이것을 복구하십시오):",
  "Card assignments": "카드 배정",
  "Could not load the data counts.": "자료 개수를 불러올수 없습니다.",
  "Daily attendance": "일별 출퇴근",
  "Data reset": "자료 초기화",
  "Delete all data": "모든 자료 삭제",
  "Delete all developers, cards and activity, to start again with the same users, readers and stores.": "모든 개발자, 카드와 활동기록을 삭제하고 같은 사용자, 인식기, 매장으로 다시 시작합니다.",
  "Deleted": "삭제됨",
  "Developer accounts": "개발자 계정",
  "Developers, cards and everything recorded about them.": "개발자, 카드와 그에 대한 모든 기록입니다.",
  "Kept": "남김",
  "Only admins can reset the data.": "관리자만 자료를 초기화할수 있습니다.",
  "Purchase items": "판매 품목",
  "Rows deleted": "삭제된 행",
  "Seller payouts": "판매 지급",
  "Stock movements": "재고 이동",
  "System": "체계",
  "The data was deleted.": "자료를 삭제했습니다.",
  "There is no data to delete.": "삭제할 자료가 없습니다.",
  "To confirm, type": "확인하려면 입력하십시오:",
  "Users and roles, readers, buildings, sellers and goods. Seller balances start at 0; each good keeps its current stock.": "사용자와 권한, 인식기, 건물, 판매자와 상품입니다. 판매 잔고는 0부터 시작하고 상품마다 현재 재고는 남습니다.",
  "Who is inside": "안에 있는 사람",
  "A database backup is made first; if it fails, nothing is deleted. The audit log starts again with one entry for this reset.": "먼저 자료기지를 예비복사합니다. 실패하면 아무것도 삭제하지 않습니다. 활동기록은 이 초기화 기록 하나로 다시 시작합니다.",
  "Type the confirmation phrase exactly to delete all data.": "모든 자료를 삭제하려면 확인문구를 정확히 입력하십시오.",
  "The backup before the reset failed, so nothing was deleted.": "초기화전 예비복사가 실패하여 아무것도 삭제하지 않았습니다.",
  "…or any card UID (e.g. an unknown card)": "또는 임의의 카드 UID (미등록 카드)",
  "1. Tap the card": "1. 카드를 대십시오",
  "2. Assign": "2. 배정",
  "A building that still has doors cannot be deleted.": "출입문이 있는 건물은 지울수 없습니다.",
  "A building that still has doors stays in place and the server reports that it is in use.": "출입문이 남아 있으면 건물은 그대로 있고, 봉사기는 사용중이라고 알립니다.",
  "A card assign reader is recognised by its ID alone (e.g. Master1). Tapping a card on it fills the New card and Assign card pages. Each ID can be used once.": "카드 배정 발급기는 ID만으로 알아봅니다(례: Master1). ID마다 한번만 쓸수 있습니다.",
  "A debit cannot use money already reserved by open payouts.": "결제중입니다.",
  "a developer of another building": "다른 건물의 개발자",
  "A door unit has a building and its own fixed IP; units of one door share the code. Till and card assign readers are recognised by their code alone.": "출입문 장치에는 건물과 고정 IP가 있으며 한 출입문의 장치들은 같은 코드를 씁니다.",
  "A last working day does not change status or release the card. Set status to Terminated when someone leaves. Delete is a soft delete.": "개발자퇴소",
  "A new card is registered as soon as it is tapped. Then add a label or assign it.": "카드를 인식하는 즉시 등록됩니다. 그다음 카드번호를 넣거나 배정하십시오.",
  "A reason is required.": "리유가 필요합니다.",
  "A till or counter where goods are sold. Delete is a soft delete.": "물건을 파는 판매소입니다.",
  "A till reader is not tied to a counter. It is recognised by its ID alone, from any PC. Each ID can be used once.": "카드인식기는 판매장소에 고정되지 않습니다.",
  "A user can have several roles. You can only grant roles you are allowed to grant.": "사용자는 권한을 여러개 가질수 있습니다.",
  Accepted: "승인",
  Account: "계정",
  Accounts: "계정",
  "Accounts that can sign in": "가입할수 있는 계정",
  "Accounts, roles, and who can sign in.": "계정, 권한, 그리고 누가 가입할수 있는지입니다.",
  Action: "동작",
  Actions: "동작",
  Active: "활성",
  "Active staff who are not inside any building.": "어느 건물에도 없는 근무중 직원입니다.",
  Actor: "실행한 사람",
  Add: "추가",
  "Add a missing moment. Choose Out when someone is still counted inside because they never scanned out.": "빠진 시간을 넣습니다. 나간 기록이 없어 안에 있는것으로 남으면 외출로 하십시오.",
  "Add item": "품목 추가",
  "Add money": "돈 넣기",
  "Add record": "기록 추가",
  "Add role": "권한 추가",
  Adjust: "조정",
  Adjustment: "조정",
  After: "이후",
  All: "전체",
  "All developers": "전체 개발자",
  "All rows": "전체 행",
  "All staff": "전체 인원",
  "All users": "전체 사용자",
  "Allowed door IP": "출입문 허용 IP",
  "Allowed IP": "허용 IP",
  "Already assigned to": "이미 배정됨",
  "Already inactive": "이미 비활성",
  "Alt text": "그림 설명",
  Amount: "금액",
  "Amount is a decimal, such as 25.00.": "금액은 25.00처럼 소수입니다.",
  "Any birthday month": "생일 달 전체",
  "Any source": "모든 출처",
  "Any type": "모든 종류",
  Apply: "적용",
  Approve: "승인",
  Approved: "승인됨",
  Apr: "4월",
  Assign: "배정",
  "Assign card": "카드 배정",
  "Assign it now": "지금 배정",
  Assigned: "배정됨",
  "Assigned by": "배정한 사람",
  Assignment: "배정",
  Assignments: "배정",
  Attendance: "출퇴근",
  "Attendance day": "출퇴근 날",
  "Attendance days": "출퇴근 날",
  "Attendance door": "출입문",
  "Attendance record": "출입 기록",
  Audit: "활동기록",
  "Audit event": "활동기록 사건",
  "Audit events": "활동기록 사건",
  Aug: "8월",
  Available: "가능",
  "Available balance is the balance minus money reserved by open payouts.": "쓸수있는 잔고는 잔고에서 진행중인 결제에 속한 돈을 제외한것입니다.",
  Balance: "잔고",
  "Balance after": "이후 잔고",
  "Balance after deposit": "입금후 잔고",
  "Balance after pay ·": "결제후 잔고 ·",
  Balances: "잔고",
  Before: "이전",
  Birthday: "생일",
  "Birthdays this month": "이번달 생일",
  Block: "차단",
  Blocked: "차단",
  "Book ahead": "예약",
  "Book and pay": "예약하고 결제",
  BOOKED: "예약됨",
  Booking: "예약",
  bookings: "건",
  Bookings: "예약",
  "Bookings are final and cannot be refunded.": "예약은 끝나면 되돌릴수 없습니다.",
  Both: "둘 다",
  Building: "건물",
  Buildings: "건물",
  Buyer: "구매자",
  Buyers: "구매자",
  "By building": "건물별",
  "By counter": "판매소별",
  "By day": "날자별",
  "By department": "부서별",
  "By seller": "판매자별",
  "By till reader": "카드인식기별",
  "By week": "주별",
  Cancel: "취소",
  "Cancel draft": "초안 취소",
  "Cancel purchase": "판매 취소",
  cancelled: "취소",
  Cancelled: "취소됨",
  Card: "카드",
  "Card ·": "카드 ·",
  "Card assign reader": "카드발급기",
  "Card assign readers": "카드발급기",
  "Card scans": "카드 인식",
  "Card UID": "카드 UID",
  "Card was not accepted": "카드를 받지 않았습니다",
  Cards: "카드",
  "Cards are retired, not deleted, so scan history stays intact.": "카드는 지우지 않고 페기하여 인식기록이 남습니다.",
  Change: "변경",
  "Change the password for this account.": "이 계정의 암호를 바꿉니다.",
  Changes: "변경",
  Chart: "도표",
  Choose: "고르기",
  "Choose a reader": "인식기를 고르십시오",
  "Choose a time": "시간을 고르십시오",
  "Clears the spending PIN so the developer can set a new one.": "지출 PIN을 지워 개발자가 새로 정하게 합니다.",
  "Client event": "인식기 사건",
  "Client event id": "인식기 사건번호",
  Close: "닫기",
  "Close a seller later by setting status to Closed.": "판매를 끝낼때는 상태를 페점으로 바꿉니다.",
  Closed: "페점",
  "Closed this day": "이 날은 휴식입니다",
  Closes: "닫는 시각",
  "Closing time": "닫는 시각",
  Code: "코드",
  "Code (the ID the hardware sends)": "코드 (장치가 보내는 ID)",
  "Code is the short label, such as B1.": "코드는 B1처럼 짧은 표시입니다.",
  "Company management": "회사 관리",
  "Company management console": "회사 관리창",
  "Company statistics": "회사 통계",
  Confirmed: "확인됨",
  "Confirmed purchases": "확인된 판매",
  "Confirmed till sales and court bookings for each sell position.": "매장마다 확인된 계산 판매와 운동장 예약입니다.",
  "Confirmed till sales and court bookings in the period. Click a bar to open the seller.": "이 기간의 확인된 계산 판매와 운동장 예약입니다. 도표를 누르면 판매자가 열립니다.",
  Connecting: "련결중",
  Contact: "련락",
  "Contact name": "련락 이름",
  "Copy key": "열쇠 복사",
  "Correct a balance": "잔고 고치기",
  Correction: "정정",
  "Could not load company statistics.": "회사 통계를 적재할수 없습니다.",
  "Could not load developers.": "개발자를 적재할수 없습니다.",
  "Could not load occupancy.": "현재 인원을 적재할수 없습니다.",
  "Could not load scans.": "출입기록을 적재할수 없습니다.",
  "Could not load the scan log.": "출입기록을 적재할수 없습니다.",
  "Could not load users.": "사용자를 적재할수 없습니다.",
  "Could not reach the app.": "프로그람에 련결할수 없습니다.",
  "Could not sign in.": "가입할수 없습니다.",
  "Counted adjustment": "실사 조정",
  "Counted quantity": "수량",
  "counts reload every 10 seconds": "10초마다 인원을 다시 읽습니다",
  "Court bookings": "운동장 예약",
  "Courts are booked at the desk. The developer taps a card and enters a PIN.": "운동장은 관제초소에서 예약합니다. 개발자가 카드를 대고 PIN을 넣습니다.",
  "Create building": "건물 만들기",
  "Create developer": "개발자 만들기",
  "Create good": "상품 만들기",
  "Create position": "매장 만들기",
  "Create seller": "판매자 만들기",
  Created: "만든 시기",
  Currency: "화폐",
  "Current balance ·": "현재 잔고 ·",
  "Current password": "현재 암호",
  "Current PIN": "현재 PIN",
  "Current status": "현재 상태",
  "Daily attendance and manual corrections.": "일일 출퇴근과 수동 수정입니다.",
  "Daily presence will be charted here.": "일일 재실이 여기 도표로 나옵니다.",
  "Daily row": "일일 기록",
  "Daily rows for the signed-in developer.": "가입한 개발자의 일일 기록입니다.",
  Damage: "손실",
  Dark: "어둡게",
  Dashboard: "계시판",
  Date: "날자",
  Day: "날",
  Deactivate: "비활성화",
  Dec: "12월",
  Delete: "삭제",
  "Delete building": "건물 삭제",
  "Delete developer": "개발자 삭제",
  "Delete good": "상품 삭제",
  "Delete permanently": "완전 삭제",
  "Delete permanently?": "완전히 삭제하시겠습니까?",
  "Delete position": "매장 삭제",
  Department: "부서",
  "Department ·": "부서 ·",
  Deposit: "입금",
  deposits: "건",
  Deposits: "입금",
  "Deposits and spending each day.": "날마다 입금과 지출입니다.",
  "Deposits, purchases, refunds, and adjustments.": "입금, 구매, 환불, 조정입니다.",
  Description: "설명",
  Details: "내용",
  Developer: "개발자",
  "Developer ·": "개발자 ·",
  "Developer balances": "개발자 잔고",
  "Developer balances now": "지금 개발자 잔고",
  "Developer balances. Frozen accounts can still receive deposits.": "개발자 잔고입니다. 동결된 계좌도 입금은 됩니다.",
  "Developer money": "개발자 돈",
  "Developer paying": "결제하는 개발자",
  Developers: "개발자",
  Device: "인식기",
  "Device code": "인식기 코드",
  "Device request": "인식기 요청",
  "Different people recorded in this date range": "이 기간에 기록된 서로 다른 사람",
  "Different people who paid": "결제한 서로 다른 사람",
  Direction: "방향",
  "Directory, status, and each person's card and attendance.": "명부, 상태, 그리고 각 사람의 카드와 출퇴근입니다.",
  Door: "출입문",
  "Door IP": "출입문 IP",
  "Door readers and the one-time API key when a reader is created or rotated.": "출입 인식기와, 만들거나 열쇠를 바꿀 때 한번 보이는 API 열쇠입니다.",
  "Door scan": "출입문 인식",
  "Door scans": "출입 인식",
  "Door scans marked in": "입장으로 표시된 출입 인식",
  "Door scans marked out": "퇴장으로 표시된 출입 인식",
  "Door units, till readers and card assign readers. Online means the device sent a tap in the last two minutes.": "출입문 장치, 카드인식기, 카드발급기입니다. 온라인은 최근 2분 안에 카드를 읽은 장치입니다.",
  Doors: "출입문",
  "Doors are registered separately and point at this building.": "출입문은 따로 등록하고 이 건물을 가리킵니다.",
  Drafts: "초안",
  "Each bar is only that day. A person who came on more than one day is counted once above and once on each bar.": "도표는 그 날만입니다. 여러 날 온 사람은 우에는 한번, 각 도표에는 한번씩입니다.",
  "Each bar is only that week. A person who came on more than one week is counted once above and once on each bar.": "도표는 그 주만입니다. 여러 주 온 사람은 우에는 한번, 각 도표에는 한번씩입니다.",
  "Each bar is people who scanned at that building. A person who used two buildings is counted in both.": "도표마다 그 건물에서 인식한 사람입니다. 두 건물을 쓴 사람은 둘 다에 들어갑니다.",
  "Each bar is the people in that department. A person has one department, so these bars add up to People above.": "도표마다 그 부서의 사람입니다. 사람은 부서가 하나이므로 이 도표를 더하면 우의 사람과 같습니다.",
  "Each seller has its own till readers. The page never sends a card number.": "판매자마다 카드인식기가 있습니다. 이 쪽은 카드 번호를 보내지 않습니다.",
  "Each submission carries its own idempotency key.": "보낼 때마다 새 중복방지 열쇠가 붙습니다.",
  Earnings: "수입",
  "Earnings and payouts in the period, and each seller's balance now.": "이 기간의 수입과 지급, 그리고 지금 각 판매자 잔고입니다.",
  Edit: "고치기",
  "Edit a name or roles. Deactivate stops sign-in. Delete asks you to confirm before it tries to remove the account.": "이름이나 권한을 고칩니다. 비활성화하면 가입할수 없습니다. 삭제는 확인한 뒤에 계정을 없애려고 합니다.",
  Email: "전자우편",
  "Email is the sign-in name.": "전자우편이 가입 이름입니다.",
  "Employee number": "직원번호",
  "Employee number ·": "직원번호 ·",
  "Employee number and full name are required.": "직원번호와 이름은 필수입니다.",
  End: "끝",
  "End reason": "끝 리유",
  "Enter the amount, then the developer taps their card and PIN.": "금액을 넣은 뒤 개발자가 카드와 PIN을 입력합니다.",
  "Enter the amount, then the developer taps their card on the card assign reader and types their PIN.": "금액을 넣은 뒤 개발자가 카드발급기에 카드를 대고 PIN을 입력합니다.",
  "Enter your email.": "전자우편을 입력하십시오.",
  "Enter your password.": "암호를 입력하십시오.",
  "Event time": "사건 시각",
  Feb: "2월",
  Finance: "재무",
  "Finance statistics": "재무 통계",
  "Find a test developer": "시험 개발자 찾기",
  First: "처음",
  "Fixed IP of this unit": "이 장치의 고정 IP",
  Floating: "떠 있음",
  "Four to six digits. Enter the current PIN when you already have one.": "수자 네 자리부터 여섯자리입니다. 이미 있으면 현재 PIN을 넣으십시오.",
  FREE: "비어 있음",
  "Free time is open. Booked time does not show who. A click starts a card-and-PIN checkout.": "빈 시간은 예약할수 있습니다. 잡힌 시간은 누구인지 보이지 않습니다. 누르면 카드와 PIN으로 결제합니다.",
  Freeze: "동결",
  From: "부터",
  "Full name": "이름",
  "Give this card to a developer.": "이 카드를 개발자에게 줍니다.",
  Good: "상품",
  Goods: "상품",
  "Hello again": "다시 만나서 반갑습니다",
  "Hello,": "안녕하십니까,",
  Hide: "숨김",
  "Hold the card on the reader. This closes when the card is recognized.": "인식기에 카드를 대십시오. 카드가 확인되면 이 창이 닫힙니다.",
  Holder: "소지자",
  "Home address": "집 주소",
  "Home building": "소속 건물",
  Hours: "시간",
  "How many slots": "칸 수",
  Icon: "그림기호",
  Image: "사진",
  Images: "사진",
  In: "입장",
  "In scans": "입장 인식",
  Inactive: "비활성",
  "Includes drafts and cancelled purchases from the same dates.": "같은 날자의 초안과 취소된 판매도 있습니다.",
  "Initial quantity": "처음 수량",
  Inset: "안쪽",
  Inside: "내부",
  "Inside now": "지금 안에 있음",
  "Inside, but the last scan had no door": "안에 있으나 마지막 인식에 출입문이 없습니다",
  "Invalid input.": "입력자료가 옳지 않습니다.",
  Inventory: "재고",
  IP: "IP",
  "Issue a new card to the current holder and retire this one.": "지금 가진 사람에게 새 카드를 주고 이 카드는 페기합니다.",
  Items: "품목",
  "Items for sale": "판매 품목",
  "Items sold at a service position. Delete is a soft delete.": "판매소에서 파는 품목입니다. 삭제는 숨김입니다.",
  Jan: "1월",
  Jul: "7월",
  Jun: "6월",
  "Just registered": "방금 등록됨",
  "Keep current building": "지금 건물 유지",
  Kind: "종류",
  Label: "표시",
  Language: "언어",
  Last: "마지막",
  "Last day": "퇴직일",
  "Last IP": "마지막 IP",
  "Last month": "지난 달",
  "Last seen": "마지막 수신",
  "Last sign-in": "마지막 가입",
  "Last week": "지난 주",
  Username: "사용자 이름",
  "Enter your username.": "사용자 이름을 입력하십시오.",
  "Use your username and password.": "사용자 이름과 암호를 입력하십시오.",
  "Search name or username": "이름 또는 사용자 이름으로 찾기",
  "Wrong username or password.": "사용자 이름 또는 암호가 틀립니다.",
  "Type to search, or a new one": "입력하여 찾거나 새로 입력",
  "PIN desk": "PIN 창구",
  "Change PIN": "PIN 바꾸기",
  "Forgot PIN": "PIN 분실",
  "Tap card": "카드 대기",
  "Set new PIN": "새 PIN 설정",
  "New PIN again": "새 PIN 다시",
  "PIN changed for": "PIN을 바꾸었습니다:",
  "New PIN set for": "새 PIN을 설정하였습니다:",
  "No PIN yet: use Forgot PIN to set one.": "아직 PIN이 없습니다. PIN 분실로 설정하십시오.",
  "Loading the wallet…": "지갑적재중…",
  "locked until": "잠김 해제 시간",
  "TCP log": "TCP 기록",
  "Every packet the devices sent to port 9100 (request) and what the server answered (response). Kept 30 days.": "장치가 9100번 포구로 보낸 모든 요청과 봉사기의 응답입니다. 30일 동안 보관합니다.",
  "Live (refresh every 3 s)": "실시간 (3초마다 갱신)",
  Outcome: "결과",
  "From IP": "보낸 IP",
  "Device ID": "장치 ID",
  "Text in request or response": "요청 또는 응답의 글자",
  Response: "응답",
  packets: "요청",
  "Newest first. Times are UTC.": "최신순. 시간은 UTC입니다.",
  "No packets yet.": "아직 요청이 없습니다.",
  Handled: "처리됨",
  "Unknown device or address": "모르는 장치 또는 주소",
  "Invalid packet": "잘못된 요청",
  "Connection refused": "접속 거부",
  "Server error": "봉사기 오유",
  Newer: "더 새것",
  Older: "더 오랜것",
  "Last working day": "마지막 근무일",
  "Latest record is an in, and no later out has been recorded.": "마지막 기록이 입장이며 그 뒤 퇴장이 없습니다.",
  "Layout settings": "배치 설정",
  "Leave empty to keep this court": "이 운동장을 유지하려면 비우십시오",
  "Leave the seller empty when you are creating it for your own seller.": "자기 판매자면 판매자를 비우십시오.",
  "Leaving the company is a status change, not a hard delete.": "회사를 떠나는것은 상태 변경이며 완전 삭제가 아닙니다.",
  left: "나감",
  "Left after": "이후 퇴직",
  "Left before": "이전 퇴직",
  Light: "밝게",
  Line: "줄",
  "Linked user": "련결된 사용자",
  List: "목록",
  Live: "실시간",
  "Live · counts update as doors scan": "실시간 · 출입문이 인식하면 인원이 바뀝니다",
  "Live totals from the company API. Charts will sit under them.": "회사 API의 현재 합계입니다.",
  "Live updates need attendance.view": "실시간에는 출퇴근 보기 권한이 필요합니다",
  "Live updates need permission to watch this counter": "이 매장을 보려면 실시간 권한이 필요합니다",
  Location: "위치",
  Log: "기록",
  Login: "가입",
  "Login to continue": "계속하려면 가입하십시오",
  Management: "관리",
  Manager: "담당",
  "Manager user ids": "관리자 사용자 번호",
  Managers: "관리자",
  Manual: "수동",
  "Manual attendance": "수동 출퇴근",
  "Manual record": "수동 기록",
  Mar: "3월",
  "Mark paid": "지급 완료",
  "Mark processing": "처리중으로",
  "Max days ahead": "미리 예약 일수",
  "Max slots per booking": "한번에 최대 칸",
  "Max slots per day": "일일 최대 칸",
  "Max slots per person per day": "일일 한 사람 최대 칸",
  May: "5월",
  Member: "성원",
  min: "분",
  Money: "금액",
  "Money held": "가진 금액",
  "Money taken": "받은 금액",
  Move: "옮기기",
  "Move booking": "예약 옮기기",
  Movement: "이동",
  Movements: "이동",
  "Movements on the signed-in developer's wallet.": "가입한 개발자 지갑의 이동입니다.",
  "My attendance": "나의 출퇴근",
  "My attendance records": "나의 출입 기록",
  "My bookings": "나의 예약",
  "My developer profile": "나의 개발자 정보",
  "My profile": "나의 정보",
  "My purchases": "나의 구매",
  "My seller": "나의 판매",
  "My seller balance": "나의 판매 잔고",
  "My seller profile": "나의 판매자 정보",
  "My transactions": "나의 거래",
  "My wallet": "나의 지갑",
  Name: "이름",
  "Name is required.": "이름은 필수입니다.",
  "Name of this unit": "이 장치의 이름",
  "Name or employee number": "이름 또는 직원번호",
  "Name, number, or phone": "이름, 번호, 전화",
  New: "새로 만들기",
  "New building": "건물 추가",
  "New card": "카드 추가",
  "New developer": "개발자 추가",
  "New device": "인식기 추가",
  "New good": "상품 추가",
  "New label": "새 표시",
  "New password": "새 암호",
  "New PIN": "새 PIN",
  "New position": "매장 추가",
  "New purchase": "새 판매",
  "New seller": "판매자 추가",
  "New service position": "매장 추가",
  "New UID": "새 UID",
  "New user": "사용자 추가",
  "Newest card scans first.": "최근 카드 인식이 먼저입니다.",
  Next: "다음",
  No: "아니오",
  "No access": "권한 없음",
  "No assignments yet.": "배정이 없습니다.",
  "No attendance for this account.": "이 계정의 출퇴근이 없습니다.",
  "No audit events yet.": "활동기록 기록이 없습니다.",
  "No bookings for this day.": "이 날의 예약이 없습니다.",
  "No bookings yet.": "예약이 없습니다.",
  "No building": "건물 없음",
  "No buildings yet.": "건물이 없습니다.",
  "No card assign reader": "카드발급기 없음",
  "No cards yet.": "카드가 없습니다.",
  "No chart data yet": "아직 도표 자료가 없습니다",
  "No confirmed sales in this range.": "이 기간에 확인된 판매가 없습니다.",
  "No developers yet.": "개발자가 없습니다.",
  "No devices yet.": "인식기가 없습니다.",
  "No goods yet.": "상품이 없습니다.",
  "No images.": "사진이 없습니다.",
  "No items yet.": "품목이 없습니다.",
  "No login": "가입 없음",
  "No longer waiting: another purchase is scanning on this reader, or 2 minutes passed.": "더 이상 기다리지 않습니다. 다른 판매가 이 인식기에서 읽히는중이거나 2분이 지났습니다.",
  "No manager": "책임자 없음",
  "No matching developers": "맞는 개발자가 없습니다",
  "No movements yet.": "이동이 없습니다.",
  "No numbers for this chart.": "이 도표에 수자가 없습니다.",
  "No payouts yet.": "지급이 없습니다.",
  "No periods.": "시간이 없습니다.",
  "No positions yet.": "매장이 없습니다.",
  "No previous sign-in": "이전 가입 없음",
  "No purchases for this account.": "이 계정의 구매가 없습니다.",
  "No purchases in this range.": "이 기간에 판매가 없습니다.",
  "No records for this account.": "이 계정의 기록이 없습니다.",
  "No rentals are bookable.": "예약할 야외운동장이 없습니다.",
  "No roles.": "권한이 없습니다.",
  "No scans match this list.": "이 목록과 맞는 출입 기록이 없습니다.",
  "No scans yet.": "인식이 없습니다.",
  "No seller accounts yet.": "판매 계정이 없습니다.",
  "No seller transactions yet.": "판매 거래가 없습니다.",
  "No sellers yet.": "판매자가 없습니다.",
  "No store login yet": "아직 매장 가입이 없습니다",
  "No till reader is connected to this PC yet. The first card tap can still attach one.": "이 콤퓨터에 련결된 카드인식기가 아직 없습니다. 첫 카드는 그래도 붙을수 있습니다.",
  "No transactions for this account.": "이 계정의 거래가 없습니다.",
  "No transactions yet.": "거래가 없습니다.",
  "No users match this list.": "이 목록과 맞는 사용자가 없습니다.",
  "No wallets yet.": "지갑이 없습니다.",
  "Nobody is in.": "안에 있는 사람이 없습니다.",
  "Nobody is inside this selection.": "이 선택안에 사람이 없습니다.",
  "Nobody is out.": "밖에 있는 사람이 없습니다.",
  None: "없음",
  "Not assigned": "미배정",
  "Not available for this account": "이 계정에서는 볼수 없습니다",
  "Not terminated": "퇴직은 빠집니다",
  NOT_YET_OPEN: "아직 열리지 않음",
  Note: "비고",
  Notes: "비고",
  "Nothing matches this search.": "검색 결과가 없습니다.",
  "Nothing to summarize yet": "아직 요약할 내용이 없습니다",
  Nov: "11월",
  Number: "번호",
  Oct: "10월",
  of: "중",
  offline: "비직결",
  Offline: "비직결",
  OK: "확인",
  "Old password": "현재 암호",
  "On leave": "휴가",
  Online: "접속",
  "Only a zero balance can be closed.": "잔고가 0일 때만 닫을수 있습니다.",
  "Open card": "카드 열기",
  "Open draft": "바구니 열기",
  Opening: "여는중",
  "Opening time": "여는 시각",
  Opens: "여는 시각",
  "Optional: the transfer has started.": "선택: 결제가 시작되었습니다.",
  "Other court id": "다른 운동장 번호",
  Out: "퇴장",
  "Out scans": "퇴장 인식",
  Outside: "외부",
  Overview: "개요",
  "Owed to sellers now": "지금 판매자에게 줄 금액",
  Owners: "소유자",
  Paid: "지급됨",
  "Paid bookings for this day. A booking can be moved until it starts, at the same price.": "이 날의 결제된 예약입니다. 시작 전까지, 같은 금액으로 옮길수 있습니다.",
  "Paid sales": "결제된 판매",
  "Paid sales and money taken for each seller.": "판매자마다 결제된 판매와 받은 금액입니다.",
  "Paid sales are confirmed purchases. Money is the sum of those totals.": "결제된 판매는 확인된 판매입니다. 금액은 그 합계입니다.",
  "Paid sales at each service position.": "매장마다 결제된 판매입니다.",
  "Paid sales in each day of this range.": "이 기간의 날마다 결제된 판매입니다.",
  "Paid sales in each week of this range.": "이 기간의 주마다 결제된 판매입니다.",
  Password: "암호",
  PAST: "지남",
  Pay: "지급",
  Paying: "결제중",
  "Payment reference": "지급 참조",
  payments: "건",
  Payout: "지급",
  Payouts: "지급",
  "Payouts paid": "지급 완료",
  "Payouts pending": "지급 대기",
  people: "명",
  People: "사람",
  "People on file": "등록된 사람",
  "People present each day.": "날마다 나온 사람입니다.",
  "Per page": "페이지당",
  "Permission sets": "권한 묶음",
  Permissions: "권한",
  Person: "사람",
  Phone: "전화",
  "Pick a free stretch on the slot grid. The developer taps their card on the desk reader, then enters their PIN.": "빈 구간을 선택하십시오. 개발자가 창구 인식기에 카드를 대고 PIN을 넣습니다.",
  PIN: "PIN",
  "PIN again": "PIN 다시",
  "PIN locked until": "PIN 잠김 시각",
  Place: "장소",
  "Playground desk": "운동장 창구",
  Position: "판매장소",
  "Position manager": "판매장소 관리자",
  "Position manager (SELLER role)": "판매장소 책임자 (SELLER 권한)",
  Positions: "판매장소",
  "Positive amounts credit the wallet. Negative amounts debit it.": "",
  "Positive credits the seller. Negative debits them. A reason is required.": "",
  "Post adjustment": "조정 진행",
  "Post deposit": "입금 진행",
  "Post this deposit": "이 입금을 진행하겠습니까?",
  Preferences: "환경설정",
  "Present in any building.": "어느 건물이든 안에 있습니다.",
  "Present in this building.": "이 건물 안에 있습니다.",
  "Present right now": "지금 안에 있음",
  Previous: "이전",
  Price: "가격",
  "Price is a decimal and must be above 0 for a rental. The service position decides who sells it.": "가격은 소수이며 야외운동장은 0보다 커야 합니다. 어느 매장이 파는지가 정해집니다.",
  Processing: "처리중",
  Product: "물건",
  Profile: "정보",
  Purchase: "판매",
  purchases: "건",
  Purchases: "판매",
  "Purchases charged to the signed-in developer.": "가입한 개발자에게 청구된 구매입니다.",
  Purpose: "용도",
  Qty: "수량",
  Quantity: "수량",
  "Quantity after": "이후 수량",
  Reader: "인식기",
  "Reader key": "인식기 열쇠",
  "Reader on this PC": "이 콤퓨터의 인식기",
  Readers: "인식기",
  "Readers send scans with their own key, not a user session.": "인식기는 사용자 정보가 아니라 자기 열쇠로 인식을 보냅니다.",
  Reason: "리유",
  Received: "받은 시각",
  "Recent card scans, including unknown cards that can be registered.": "최근 카드 인식이며, 등록할수 있는 미등록 카드도 있습니다.",
  Recognized: "확인됨",
  Reconnecting: "다시 련결중",
  Record: "기록",
  "Record stock change": "재고 기록",
  "Recorded changes": "기록된 변경",
  Records: "기록",
  "Records are voided later, not deleted.": "기록은 지우지 않고 후에 무효로 합니다.",
  "Records that the money was handed over and debits the seller.": "결제를 기록하고 판매자 잔고를 덥니다.",
  Reference: "참조",
  Refresh: "새로고침",
  Refreshing: "읽는중",
  "Register card": "카드 등록",
  "Register every unit of a door separately: the same code (the door's ID, e.g. Door1), its own name (e.g. Door1-1) and its own fixed IP. The unit is recognised by its ID and IP.": "출입문의 장치마다 따로 등록하십시오. 같은 코드(출입문 ID, 례: Door1), 자기 이름(례: Door1-1), 자기 고정 IP를 씁니다. 장치는 ID와 IP로 알아봅니다.",
  "Register one under Readers → New device with the kind Card assign reader and the ID it sends (e.g. Master1).": "인식기 → 인식기 추가에서 종류를 카드발급기로 하고, 장치가 보내는 ID(예: Master1)로 등록하십시오.",
  "Registered readers": "등록된 인식기",
  Reject: "거절",
  "Reject scans while the card stays assigned.": "카드가 배정된 채로 인식을 거절합니다.",
  Rejected: "거절됨",
  "Rejection reason": "거절 리유",
  Remove: "삭제",
  "Remove image": "사진 삭제",
  Rental: "야외운동장",
  "Rental closes": "야외운동장 닫는 시각",
  "Rental opens": "야외운동장 여는 시각",
  "Rental schedule": "야외운동장 일정",
  "Rental slot minutes": "야외운동장 칸 분",
  Rentals: "야외운동장",
  Reopen: "다시 열기",
  Replace: "바꾸기",
  Request: "요청",
  "Request payout": "지급 요청",
  Requested: "요청됨",
  "Requested, approved, paid, rejected, or cancelled.": "요청, 승인, 지급, 거절, 취소입니다.",
  requests: "건",
  Reserved: "보류",
  "Reset PIN": "PIN 초기화",
  Restock: "입고",
  "Restock adds quantity. Damage subtracts it. Adjustment sets the counted quantity.": "입고는 수량을 더하고, 손망실은 빼며, 조정은 센 수량으로 맞춥니다.",
  "Restore defaults": "처음 설정으로",
  Result: "결과",
  Retire: "페기",
  Retired: "페기",
  Returned: "반납",
  "Returned by": "반납한 사람",
  "RFID cards": "RFID 카드",
  "RFID cards and who holds them.": "RFID 카드와 가진 사람입니다.",
  "RFID cards, assignments, and block or retire actions.": "RFID 카드, 배정, 차단과 페기입니다.",
  Role: "권한",
  Roles: "권한",
  "Roles are assigned on a user. They are not deleted here.": "권한은 사용자에게 줍니다. 여기서는 지우지 않습니다.",
  "Rotate key": "열쇠 바꾸기",
  Rules: "규칙",
  "Sales by counter": "매장별 판매",
  "Sales by seller": "판매자별 판매",
  "Sales count only counters in your buildings.": "판매는 소속 건물의 매장만 셉니다.",
  "Sales in this range": "이 기간의 판매",
  "Sales, payouts, and signed adjustments.": "판매, 지급, 서명된 조정입니다.",
  Save: "저장",
  "Save PIN": "PIN 저장",
  "Saving…": "저장중…",
  Scan: "인식",
  "Scan again": "다시 인식",
  "Scan card to book": "카드를 읽어 예약",
  "Scan card to buy": "카드를 읽어 판매",
  "Scan log": "출입 기록",
  "Scan results over time will be charted here.": "시간의 인식 결과가 여기 도표로 나옵니다.",
  scans: "건",
  Scans: "인식",
  "Scans and manual corrections for the signed-in developer.": "가입한 개발자의 인식과 수동 수정입니다.",
  Search: "검색",
  "Search matches a person's name or employee number. Voided rows stay in the list.": "이름이나 직원번호로 찾습니다. 무효 처리된 줄도 목록에 남습니다.",
  "Search matches name, employee number, and phone. The address stays on each person's page. A last working day does not change status or release a card.": "이름, 직원번호, 전화로 찾습니다. 주소는 각 사람의 쪽에 있습니다. 마지막 근무일은 상태나 카드를 바꾸지 않습니다.",
  "Search name or email": "이름 또는 전자우편 검색",
  "Search this table": "표 검색",
  "Search users": "사용자 검색",
  Sell: "판매",
  Seller: "판매자",
  "Seller (whose purchases use this reader)": "판매자 (이 인식기를 쓰는 판매)",
  "Seller adjustment": "판매자 조정",
  "Seller balance": "판매 잔고",
  "Seller balances": "판매 잔고",
  "Seller finance": "판매 정산",
  "Seller money": "판매자 돈",
  "Seller transaction": "판매 거래",
  "Seller transactions": "판매 거래",
  Sellers: "판매자",
  "Sellers are closed with a status change, not deleted.": "판매자는 지우지 않고 상태로 닫습니다.",
  "Sellers manage their own positions. Managers can manage all of them.": "판매자는 자기 매장을 다루고, 관리자는 모두 다룹니다.",
  "Sellers on file": "등록된 판매자",
  "Send scan": "인식 보내기",
  Sep: "9월",
  Serial: "일련번호",
  Service: "봉사",
  "Service position": "매장",
  "Service positions": "매장",
  "Set status to Closed when the seller stops trading.": "판매를 멈추면 상태를 페점으로 하십시오.",
  Settings: "설정",
  "Show range": "기간 보기",
  "Show slots": "시간 보기",
  Sidebar: "옆줄",
  "Sidebar collapse": "옆줄 접기",
  "Sidebar style": "옆줄 모양",
  "Sign out": "나가기",
  "Signing in…": "가입중…",
  "Signing out…": "나가는중…",
  "Simulate tap (testing only)": "카드 대기 시험 (시험만)",
  Since: "이후",
  Sites: "장소",
  SKU: "SKU",
  Slot: "칸",
  "Slot minutes": "칸 분",
  Slots: "칸",
  "slots in one booking. Who is booking is known after the card tap.": "칸입니다. 누구인지는 카드를 읽은 뒤에 압니다.",
  "Soft-deletes this good.": "이 상품을 목록에서 숨깁니다.",
  "Soft-deletes this person. Prefer Terminated when they are leaving the company.": "이 사람을 목록에서 숨깁니다. 회사를 떠나면 퇴직을 쓰십시오.",
  "Soft-deletes this position.": "이 매장을 목록에서 숨깁니다.",
  "Sorted by sales and bookings in the period.": "이 기간의 판매와 예약 순입니다.",
  Source: "출처",
  Spending: "지출",
  "Spending PIN": "지출 PIN",
  "Spending stops. Deposits still work.": "지출은 멈추고 입금은 됩니다.",
  Start: "시작",
  "Start date": "시작일",
  Started: "입사",
  Statistics: "통계",
  Status: "상태",
  "Still inside": "아직 안에 있음",
  Stock: "재고",
  "Stock changes after creation go through the stock action.": "만든 뒤의 재고는 재고 동작으로 바꿉니다.",
  "Stock changes recorded against goods.": "상품에 기록된 재고 변경입니다.",
  "Store login": "매장 가입",
  "Store login (SELLER role)": "매장 가입 (SELLER 권한)",
  "Store sales": "매장 판매",
  "Stored daily rows": "저장된 일일 기록",
  "Submit scan": "인식 제출",
  "Sum of paid totals": "결제된 합계",
  Summary: "요약",
  Suspended: "정지",
  "Tables and filters for this section will sit here.": "이 구역의 표와 거름이 여기 있습니다.",
  "Take an unassigned card out of circulation.": "배정되지 않은 카드를 사용에서 삭제합니다.",
  "Take the card back. The history stays.": "카드를 돌려받습니다. 기록은 남습니다.",
  taken: "예약됨",
  "Tap a card first.": "먼저 카드를 대십시오.",
  "Tap another card to replace it.": "바꿀 다른 카드를 대십시오.",
  "Tap card to deposit": "카드를 읽어 입금",
  "Tap the card on a card assign reader, then choose the developer and their building.": "카드발급기에 카드를 댄 뒤 개발자와 건물을 고르십시오.",
  "Tap the card on a reader": "인식기에 카드를 대십시오",
  Terminated: "퇴직",
  "That stretch includes a time that is taken or closed.": "그 구간에는 잡혔거나 닫힌 시간이 있습니다.",
  "The amount cannot exceed the available balance. Leave the seller empty to use your own seller.": "금액은 쓸수 있는 잔고를 넘을수 없습니다. 자기 판매자면 판매자를 비우십시오.",
  "The card is tapped on the seller's till reader (chosen on the next page if the seller has several).": "판매자의 카드인식기에 카드를 댑니다(인식기가 여러개면 다음에서 고릅니다).",
  "The card's UID appears here as soon as the reader sends it.": "인식기가 보내면 카드 UID가 여기에 나타납니다.",
  "The code must match the ID the hardware sends, such as Door1 or Reader2.": "코드는 장치가 보내는 ID와 같아야 합니다. Door1, Reader2처럼.",
  "The developer taps their card and PIN on the next screen.": "다음 쪽에서 개발자가 카드와 PIN을 입력합니다.",
  "The developer types a new 4-6 digit purchase PIN twice.": "개발자가 새 구매 PIN(4자리)을 두 번 입력합니다.",
  "The fill is who is present right now. The number after “of” is that building’s developers. All staff uses every active developer.": "채움은 지금 안에 있는 사람입니다. “중” 뒤의 수는 그 건물의 개발자입니다. 전체 인원은 근무중인 개발자 모두입니다.",
  "The list could not be loaded.": "목록을 불러오지 못했습니다.",
  "The old key stops working immediately. Copy the new key before you leave. You will not see it again.": "옛 열쇠는 즉시 멈춥니다. 떠나기 전에 새 열쇠를 복사하십시오. 다시 보이지 않습니다.",
  "The password rules are checked by the server.": "암호 규칙은 봉사기가 확인합니다.",
  "The person signed in on this browser.": "이 열람기에 가입한 사람입니다.",
  "The requester cannot approve their own payout.": "요청한 사람은 자기 지급을 승인할수 없습니다.",
  "The row stays in history with this reason.": "이 리유와 함께 기록에 남습니다.",
  "The same client event id is accepted once. A repeat returns the original result.": "같은 인식기 사건 번호는 한번만 받습니다. 반복은 처음 결과를 돌려줍니다.",
  "The service position owns the goods that can be added. The reader is found from this computer's address.": "매장이 넣을수 있는 상품을 가집니다. 인식기는 이 콤퓨터 주소로 찾습니다.",
  "The till reader is the one plugged into this PC. The page never sends a card number.": "카드인식기는 이 PC에 꽂힌 것입니다. 이 쪽은 카드 번호를 보내지 않습니다.",
  "The UID is printed on the card and sent by readers.": "UID는 카드에 찍혀 있고 인식기가 보냅니다.",
  Theme: "모양",
  "Theme and sidebar behavior.": "모양과 옆줄의 동작입니다.",
  "There is no delete. Clear Active later to turn a device off. Registration still shows an API key once, even for a door that uses a fixed IP.": "삭제는 없습니다. 후에 근무중을 끄면 장치가 꺼집니다. 등록 때 API 열쇠는 한번 보이며, 고정 IP 출입문도 그렇습니다.",
  "These use the signed-in account. The server returns an error if you have no matching profile.": "가입한 계정을 씁니다. 맞는 정보이 없으면 봉사기가 오류를 줍니다.",
  "This account cannot see card taps.": "이 계정은 카드 읽기를 볼수 없습니다.",
  "This account has no company-wide lists.": "이 계정에는 회사 전체 목록이 없습니다.",
  "This area is reserved for a chart.": "도표가 들어올 자리입니다.",
  "This card belongs to a developer of another building.": "이 카드는 다른 건물의 개발자 것입니다.",
  "This card can't be assigned. Unassign it on the card page first, or tap another card.": "이 카드는 배정할수 없습니다. 카드 쪽에서 먼저 배정을 풀거나 다른 카드를 대십시오.",
  "This card is blocked or retired. Tap another card.": "이 카드는 차단되었거나 페기되었습니다. 다른 카드를 대십시오.",
  "This card is not assigned to anyone. Tap another card.": "이 카드는 누구에게도 배정되지 않았습니다. 다른 카드를 대십시오.",
  "This card was already registered.": "이 카드는 이미 등록되어 있습니다.",
  "This deposit cannot be undone.": "이 입금은 되돌릴수 없습니다.",
  "this developer": "이 개발자",
  "This key is shown only once. Copy it before you leave the page.": "이 열쇠는 한번만 보입니다. 떠나기 전에 복사하십시오.",
  "This month": "이번 달",
  "This payment cannot be undone.": "이 결제는 되돌릴수 없습니다.",
  "This seller has no till reader. Ask an admin to assign one (Readers → the reader's Seller).": "이 판매자에게는 카드인식기가 없습니다. 관리자에게 배정을 요청하십시오(인식기 → 해당 인식기의 판매자).",
  "This week": "이번 주",
  Till: "계산",
  "Till orders": "계산 주문",
  "Till reader": "카드인식기",
  "Till readers": "카드인식기",
  "Till sales": "계산 판매",
  "Till sales and bookings": "계산 판매와 예약",
  Time: "시간",
  Title: "직함",
  to: "~",
  To: "까지",
  "To pay ·": "낼 금액 ·",
  Today: "오늘",
  "Toggle Sidebar": "옆줄 접기",
  total: "합계",
  Total: "합계",
  "Track stock": "재고 추적",
  Transaction: "거래",
  Transactions: "거래",
  Type: "종류",
  UID: "UID",
  Unassign: "배정 해제",
  Unassigned: "미배정",
  Unblock: "차단 해제",
  Unfreeze: "동결 해제",
  Unknown: "미등록",
  Until: "까지",
  "Until it starts, move this booking to another time or another court of the same seller. The new time must cost the same. No card tap.": "시작 전까지 같은 판매자의 다른 시간이나 다른 운동장으로 옮깁니다. 새 시간은 같은 금액이어야 합니다. 카드는 필요 없습니다.",
  "Up to": "한번에 최대",
  "Update password": "암호 바꾸기",
  "Update qty": "수량 고치기",
  Updated: "수정",
  "Upload image": "사진 올리기",
  "Use this reader": "이 인식기 사용",
  "Use your company email and password.": "회사 전자우편과 암호를 입력하십시오.",
  User: "사용자",
  "User agent": "사용자 프로그램",
  users: "명",
  Users: "사용자",
  Version: "판",
  Void: "무효",
  "Void record": "기록 무효",
  "Voided at": "무효 시각",
  "Waiting for a card…": "카드 대기…",
  "Waiting for the card": "카드 대기",
  "Waiting for the next door scan.": "다음 출입 인식을 기다립니다.",
  Wallet: "지갑",
  "Wallet transactions": "지갑 거래",
  Wallets: "지갑",
  What: "내용",
  "What changed, who changed it, and the previous and next values.": "무엇이 바뀌었는지, 누가 바꿨는지, 이전 값과 다음 값입니다.",
  When: "일시",
  "Which reader was used for each paid sale.": "결제된 판매에 쓰인 인식기입니다.",
  Who: "누구",
  "Who changed what, with the previous and next values.": "누가 무엇을 바꿨는지, 이전 값과 다음 값입니다.",
  "Who held which card, including returned and replaced cards.": "누가 어느 카드를 가졌는지, 반납과 교체도 있습니다.",
  "Withdraw a request that has not been approved.": "아직 승인되지 않은 요청을 거둡니다.",
  "Worked seconds": "근무 초",
  Workspace: "작업공간",
  Yes: "예",
  "You cannot approve a payout you requested.": "자신이 요청한 지급은 승인할수 없습니다.",
  "Your account cannot add attendance records.": "이 계정은 출입 기록을 넣을수 없습니다.",
  "Your account cannot adjust balances.": "이 계정은 잔고를 조정할수 없습니다.",
  "Your account cannot adjust seller balances.": "이 계정은 판매 잔고를 조정할수 없습니다.",
  "Your account cannot assign cards.": "이 계정은 카드를 배정할수 없습니다.",
  "Your account cannot create buildings.": "이 계정은 건물을 만들수 없습니다.",
  "Your account cannot create developers.": "이 계정은 개발자를 만들수 없습니다.",
  "Your account cannot create goods.": "이 계정은 상품을 만들수 없습니다.",
  "Your account cannot create sellers.": "이 계정은 판매자를 만들수 없습니다.",
  "Your account cannot create service positions.": "이 계정은 매장을 만들수 없습니다.",
  "Your account cannot create users.": "이 계정은 사용자를 만들수 없습니다.",
  "Your account cannot open a till draft.": "이 계정은 계산 초안을 열수 없습니다.",
  "Your account cannot open attendance statistics.": "이 계정은 출퇴근 통계를 열수 없습니다.",
  "Your account cannot open buildings.": "이 계정은 건물을 열수 없습니다.",
  "Your account cannot open cards.": "이 계정은 카드를 열수 없습니다.",
  "Your account cannot open company statistics.": "이 계정은 회사 통계를 열수 없습니다.",
  "Your account cannot open developers.": "이 계정은 개발자를 열수 없습니다.",
  "Your account cannot open finance statistics.": "이 계정은 재무 통계를 열수 없습니다.",
  "Your account cannot open readers.": "이 계정은 인식기를 열수 없습니다.",
  "Your account cannot open roles.": "이 계정은 권한을 열수 없습니다.",
  "Your account cannot open scans.": "이 계정은 인식을 열수 없습니다.",
  "Your account cannot open the audit log.": "이 계정은 활동기록 기록을 열수 없습니다.",
  "Your account cannot open the scan log.": "이 계정은 출입 기록을 열수 없습니다.",
  "Your account cannot open this section.": "이 계정은 이 구역을 열수 없습니다.",
  "Your account cannot open users.": "이 계정은 사용자를 열수 없습니다.",
  "Your account cannot post deposits.": "이 계정은 입금을 올릴수 없습니다.",
  "Your account cannot register cards.": "이 계정은 카드를 등록할수 없습니다.",
  "Your account cannot register devices.": "이 계정은 인식기를 등록할수 없습니다.",
  "Your account cannot submit reader scans.": "이 계정은 인식기 인식을 보낼수 없습니다.",
  "Your own developer profile.": "자신의 개발자 정보입니다.",
  "Your own seller profile.": "자신의 판매자 정보입니다.",
  "Your records": "자신의 기록",
};
