/** Where each permission shows up in the web app, to help choose. */
export const PAGES: Record<string, string> = {
  "user.view": "Users",
  "user.manage": "New user, a user's page",
  "role.view": "Roles",
  "role.assign": "A user's roles",
  "role.manage": "Roles: new role, change a role",
  "audit.view": "Audit",
  "stats.view": "Dashboard, Company statistics",
  "developer.view": "Developers",
  "developer.create": "New developer, Excel import",
  "developer.update": "A developer's page, Excel import",
  "developer.delete": "A developer's page",
  "card.view": "Cards, Assignments, a developer's card",
  "card.register": "New card, a card's label",
  "card.assign": "Assign card, a developer's card, Excel import",
  "card.block": "A card's page: Block, Unblock",
  "reader.view": "Readers, Buildings",
  "reader.manage": "New device, a reader's page, a store's till readers",
  "building.manage": "Buildings: new, rename, delete",
  "scan.view": "Scans",
  "attendance.view": "Attendance: Current status, Statistics, Scan log",
  "attendance.correct": "Attendance: Manual record",
  "finance.view": "Finance: Statistics, Wallets, Transactions",
  "finance.deposit": "Finance: Deposit, PIN desk, Excel import",
  "finance.adjust": "Finance: Adjustment",
  "purchase.view": "Purchases",
  "purchase.create": "Purchases: New",
  "purchase.confirm": "The till: take payment",
  "purchase.cancel": "A purchase's page: Cancel",
  "booking.view": "Playground: Courts, Playground desk",
  "booking.create": "A court's page: book",
  "booking.change": "A booking's page: move",
  "booking.cancel": "A court checkout: cancel",
  "court.manage": "Playground: New court, a court's settings",
  "seller.view": "Sellers: All stores, Counters",
  "seller.create": "Sellers: New store",
  "seller.update": "A store's page",
  "counter.manage": "A store's counters, a counter's page",
  "good.view": "Goods, Inventory",
  "good.create": "Goods: New",
  "good.update": "A good's page",
  "good.delete": "A good's page: Delete",
  "good.stock": "Inventory: Add stock",
  "excel.export": "Excel, every Download Excel button",
  "excel.import": "Excel: Import",
  "system.tcp_log": "Readers: TCP log",
  "system.backup": "System: Backups",
  "system.delete_records": "Delete for good, on each record's page",
  "system.data_reset": "System: Data reset",
};
