/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attendance/daily/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `me` lists the caller's own rows (any authenticated user with a developer profile). */
        get: operations["attendance_daily_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/daily/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `me` lists the caller's own rows (any authenticated user with a developer profile). */
        get: operations["attendance_daily_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/daily/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `me` lists the caller's own rows (any authenticated user with a developer profile). */
        get: operations["attendance_daily_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/records/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Records are never deleted; wrong ones are voided with a reason. */
        get: operations["attendance_records_list"];
        put?: never;
        /** @description Add a missing attendance moment (e.g. the developer forgot to scan). */
        post: operations["attendance_records_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/records/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Records are never deleted; wrong ones are voided with a reason. */
        get: operations["attendance_records_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/records/{id}/void/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Records are never deleted; wrong ones are voided with a reason. */
        post: operations["attendance_records_void_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/records/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Records are never deleted; wrong ones are voided with a reason. */
        get: operations["attendance_records_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit_logs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/developers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        get: operations["developers_list"];
        put?: never;
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        post: operations["developers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/developers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        get: operations["developers_retrieve"];
        put?: never;
        post?: never;
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        delete: operations["developers_destroy"];
        options?: never;
        head?: never;
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        patch: operations["developers_partial_update"];
        trace?: never;
    };
    "/api/v1/developers/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description DELETE is a soft delete. For someone leaving the company, set `status=TERMINATED`. */
        get: operations["developers_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rfid_assignments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/assignments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rfid_assignments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        get: operations["rfid_cards_list"];
        put?: never;
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        post: operations["rfid_cards_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        get: operations["rfid_cards_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        patch: operations["rfid_cards_partial_update"];
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        post: operations["rfid_cards_assign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/block/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reject all scans of this card; it stays assigned (e.g. lost, pending replacement). */
        post: operations["rfid_cards_block_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/replace/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Give the holder of this card a new card; this card is retired. Returns the new card. */
        post: operations["rfid_cards_replace_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/retire/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Take an unassigned card out of circulation permanently (broken, destroyed). */
        post: operations["rfid_cards_retire_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/unassign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        post: operations["rfid_cards_unassign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/cards/{id}/unblock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cards are never deleted: retire them instead, so scan history stays intact. */
        post: operations["rfid_cards_unblock_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Deactivate a reader with `PATCH {"is_active": false}`; its key stops working. */
        get: operations["rfid_devices_list"];
        put?: never;
        /** @description Deactivate a reader with `PATCH {"is_active": false}`; its key stops working. */
        post: operations["rfid_devices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/devices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Deactivate a reader with `PATCH {"is_active": false}`; its key stops working. */
        get: operations["rfid_devices_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Deactivate a reader with `PATCH {"is_active": false}`; its key stops working. */
        patch: operations["rfid_devices_partial_update"];
        trace?: never;
    };
    "/api/v1/rfid/devices/{id}/rotate-key/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deactivate a reader with `PATCH {"is_active": false}`; its key stops working. */
        post: operations["rfid_devices_rotate_key_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET: scan history for staff. POST: readers submit scans (`Authorization: Device <key>`). */
        get: operations["rfid_events_list"];
        put?: never;
        /** @description Returns 201 for a new scan, 200 when `client_event_id` was already seen. */
        post: operations["rfid_events_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET: scan history for staff. POST: readers submit scans (`Authorization: Device <key>`). */
        get: operations["rfid_events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        get: operations["users_list"];
        put?: never;
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/v1/users/{id}/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        post: operations["users_roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles/{role_code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Users are never hard-deleted; deactivate with `PATCH {"is_active": false}`. */
        delete: operations["users_roles_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `IN` - In
         *     * `OUT` - Out
         *     * `SCAN` - Scan (direction not classified)
         * @enum {string}
         */
        AttendanceEventTypeEnum: "IN" | "OUT" | "SCAN";
        AttendanceRecord: {
            readonly id: number;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /**
             * Format: date
             * @description Company-local working day this record counts for.
             */
            readonly work_date: string;
            /** Format: date-time */
            readonly event_time: string;
            readonly event_type: components["schemas"]["AttendanceEventTypeEnum"];
            readonly source: components["schemas"]["SourceEnum"];
            readonly device_code: string;
            readonly rfid_event: number | null;
            readonly note: string;
            readonly created_by: number | null;
            readonly is_void: boolean;
            readonly void_reason: string;
            readonly voided_by: number | null;
            /** Format: date-time */
            readonly voided_at: string | null;
        };
        AuditLog: {
            readonly id: number;
            /** @description Null for system actions (Celery tasks, RFID devices, migrations). */
            actor?: number | null;
            actor_email?: string;
            action: string;
            entity_type: string;
            entity_id: string;
            old_values?: unknown;
            new_values?: unknown;
            ip_address?: string | null;
            user_agent?: string;
            request_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CardAssignRequest: {
            developer: number;
        };
        CardReasonRequest: {
            /** @default  */
            reason: string;
        };
        CardReplaceRequest: {
            /** @description Registered automatically if it is a new card. */
            new_card_uid: string;
            new_card_label?: string;
            /** @default  */
            reason: string;
        };
        /**
         * @description * `ACTIVE` - Active
         *     * `BLOCKED` - Blocked
         *     * `RETIRED` - Retired
         * @enum {string}
         */
        CardStatusEnum: "ACTIVE" | "BLOCKED" | "RETIRED";
        CurrentAssignment: {
            readonly id: number;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /** Format: date-time */
            assigned_at?: string;
        };
        CurrentAssignmentRequest: {
            /** Format: date-time */
            assigned_at?: string;
        };
        DailyAttendance: {
            readonly id: number;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /** Format: date */
            readonly work_date: string;
            /** Format: date-time */
            readonly first_seen: string;
            /** Format: date-time */
            readonly last_seen: string | null;
            readonly record_count: number;
            readonly worked_seconds: number;
            /** Format: double */
            readonly worked_hours: number;
            readonly status: components["schemas"]["DailyAttendanceStatusEnum"];
        };
        /**
         * @description * `PRESENT` - Present
         *     * `INCOMPLETE` - Incomplete (missing or unpaired scan)
         * @enum {string}
         */
        DailyAttendanceStatusEnum: "PRESENT" | "INCOMPLETE";
        Developer: {
            readonly id: number;
            user?: number | null;
            employee_number: string;
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            department?: string;
            position_title?: string;
            manager?: number | null;
            readonly manager_detail: components["schemas"]["DeveloperSummary"];
            /** Format: date */
            start_date?: string | null;
            status?: components["schemas"]["DeveloperStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DeveloperRequest: {
            user?: number | null;
            employee_number: string;
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            department?: string;
            position_title?: string;
            manager?: number | null;
            /** Format: date */
            start_date?: string | null;
            status?: components["schemas"]["DeveloperStatusEnum"];
        };
        /**
         * @description * `ACTIVE` - Active
         *     * `ON_LEAVE` - On leave
         *     * `SUSPENDED` - Suspended
         *     * `TERMINATED` - Terminated
         * @enum {string}
         */
        DeveloperStatusEnum: "ACTIVE" | "ON_LEAVE" | "SUSPENDED" | "TERMINATED";
        /** @description Compact developer reference embedded by other modules (RFID, attendance, ...). */
        DeveloperSummary: {
            readonly id: number;
            employee_number: string;
            full_name: string;
            department?: string;
        };
        /** @description Compact developer reference embedded by other modules (RFID, attendance, ...). */
        DeveloperSummaryRequest: {
            employee_number: string;
            full_name: string;
            department?: string;
        };
        /**
         * @description * `IN` - Entrance
         *     * `OUT` - Exit
         *     * `BOTH` - Entrance and exit
         * @enum {string}
         */
        DirectionEnum: "IN" | "OUT" | "BOTH";
        /**
         * @description * `RETURNED` - Returned
         *     * `REPLACED` - Replaced
         *     * `DEVELOPER_LEFT` - Developer left
         *     * `DEVELOPER_DELETED` - Developer record deleted
         * @enum {string}
         */
        EndReasonEnum: "RETURNED" | "REPLACED" | "DEVELOPER_LEFT" | "DEVELOPER_DELETED";
        LogoutRequest: {
            refresh: string;
        };
        ManualRecordRequest: {
            developer: number;
            /** Format: date-time */
            event_time: string;
            /** @description Why the record is being added. */
            note: string;
        };
        Me: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly is_active: boolean;
            readonly roles: string[];
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
            readonly permissions: string[];
        };
        MyDeveloperProfile: {
            readonly id: number;
            readonly employee_number: string;
            readonly full_name: string;
            /** Format: email */
            readonly email: string;
            readonly phone: string;
            readonly department: string;
            readonly position_title: string;
            readonly manager: components["schemas"]["DeveloperSummary"];
            /** Format: date */
            readonly start_date: string | null;
            readonly status: components["schemas"]["DeveloperStatusEnum"];
        };
        PaginatedAttendanceRecordList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AttendanceRecord"][];
        };
        PaginatedAuditLogList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AuditLog"][];
        };
        PaginatedDailyAttendanceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DailyAttendance"][];
        };
        PaginatedDeveloperList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Developer"][];
        };
        PaginatedRFIDCardAssignmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RFIDCardAssignment"][];
        };
        PaginatedRFIDCardList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RFIDCard"][];
        };
        PaginatedRFIDDeviceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RFIDDevice"][];
        };
        PaginatedRFIDEventList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RFIDEvent"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        PasswordChangeRequest: {
            old_password: string;
            new_password: string;
        };
        PatchedDeveloperRequest: {
            user?: number | null;
            employee_number?: string;
            full_name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            department?: string;
            position_title?: string;
            manager?: number | null;
            /** Format: date */
            start_date?: string | null;
            status?: components["schemas"]["DeveloperStatusEnum"];
        };
        PatchedRFIDCardUpdateRequest: {
            /** @description Number printed on the card. */
            label?: string;
            notes?: string;
        };
        PatchedRFIDDeviceRequest: {
            /** @description e.g. READER-001 */
            code?: string;
            name?: string;
            location?: string;
            purpose?: components["schemas"]["PurposeEnum"];
            /**
             * @description Used by the attendance 'device' rule to label scans IN/OUT.
             *
             *     * `IN` - Entrance
             *     * `OUT` - Exit
             *     * `BOTH` - Entrance and exit
             */
            direction?: components["schemas"]["DirectionEnum"];
            is_active?: boolean;
        };
        PatchedUserUpdateRequest: {
            full_name?: string;
            is_active?: boolean;
        };
        /**
         * @description * `ATTENDANCE` - Attendance
         * @enum {string}
         */
        PurposeEnum: "ATTENDANCE";
        RFIDCard: {
            readonly id: number;
            uid: string;
            /** @description Number printed on the card. */
            label?: string;
            readonly status: components["schemas"]["CardStatusEnum"];
            readonly status_reason: string;
            notes?: string;
            readonly current_assignment: components["schemas"]["CurrentAssignment"] | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        RFIDCardAssignment: {
            readonly id: number;
            readonly card: number;
            readonly card_uid: string;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /** Format: date-time */
            readonly assigned_at: string;
            readonly assigned_by: number | null;
            /** Format: date-time */
            readonly unassigned_at: string | null;
            readonly unassigned_by: number | null;
            readonly end_reason: components["schemas"]["EndReasonEnum"];
        };
        RFIDCardRequest: {
            uid: string;
            /** @description Number printed on the card. */
            label?: string;
            notes?: string;
        };
        RFIDCardUpdate: {
            /** @description Number printed on the card. */
            label?: string;
            notes?: string;
        };
        RFIDDevice: {
            readonly id: number;
            /** @description e.g. READER-001 */
            code: string;
            name?: string;
            location?: string;
            purpose?: components["schemas"]["PurposeEnum"];
            /**
             * @description Used by the attendance 'device' rule to label scans IN/OUT.
             *
             *     * `IN` - Entrance
             *     * `OUT` - Exit
             *     * `BOTH` - Entrance and exit
             */
            direction?: components["schemas"]["DirectionEnum"];
            is_active?: boolean;
            readonly api_key_prefix: string;
            /** Format: date-time */
            readonly last_seen_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        RFIDDeviceRequest: {
            /** @description e.g. READER-001 */
            code: string;
            name?: string;
            location?: string;
            purpose?: components["schemas"]["PurposeEnum"];
            /**
             * @description Used by the attendance 'device' rule to label scans IN/OUT.
             *
             *     * `IN` - Entrance
             *     * `OUT` - Exit
             *     * `BOTH` - Entrance and exit
             */
            direction?: components["schemas"]["DirectionEnum"];
            is_active?: boolean;
        };
        RFIDDeviceWithKey: {
            readonly id: number;
            /** @description e.g. READER-001 */
            code: string;
            name?: string;
            location?: string;
            purpose?: components["schemas"]["PurposeEnum"];
            /**
             * @description Used by the attendance 'device' rule to label scans IN/OUT.
             *
             *     * `IN` - Entrance
             *     * `OUT` - Exit
             *     * `BOTH` - Entrance and exit
             */
            direction?: components["schemas"]["DirectionEnum"];
            is_active?: boolean;
            readonly api_key_prefix: string;
            /** Format: date-time */
            readonly last_seen_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** @description Shown only once. Configure the reader with it now. */
            readonly api_key: string;
        };
        RFIDEvent: {
            readonly id: number;
            readonly device: number;
            readonly device_code: string;
            /** @description Reader-generated id; a retried request with the same id is not stored twice. */
            readonly client_event_id: string;
            readonly uid: string;
            readonly card: number | null;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /** Format: date-time */
            readonly event_time: string;
            /** Format: date-time */
            readonly received_at: string;
            readonly result: components["schemas"]["ResultEnum"];
        };
        /**
         * @description * `ACCEPTED` - Accepted
         *     * `DUPLICATE` - Duplicate (debounced)
         *     * `UNKNOWN_CARD` - Unknown card
         *     * `UNASSIGNED_CARD` - Card not assigned
         *     * `BLOCKED_CARD` - Card blocked
         *     * `RETIRED_CARD` - Card retired
         *     * `INACTIVE_DEVELOPER` - Developer not active
         * @enum {string}
         */
        ResultEnum: "ACCEPTED" | "DUPLICATE" | "UNKNOWN_CARD" | "UNASSIGNED_CARD" | "BLOCKED_CARD" | "RETIRED_CARD" | "INACTIVE_DEVELOPER";
        Role: {
            readonly id: number;
            code: string;
            name: string;
            description?: string;
            is_system?: boolean;
            readonly permissions: string[];
        };
        RoleAssignRequest: {
            role: string;
        };
        /** @description Payload a reader sends. */
        ScanRequest: {
            uid: string;
            /** @description Optional; must match the authenticated reader's code. */
            device_id?: string;
            /** Format: date-time */
            event_time?: string;
            /** @default  */
            client_event_id: string;
        };
        ScanResponse: {
            readonly id: number;
            readonly result: components["schemas"]["ResultEnum"];
            readonly accepted: boolean;
            readonly developer: components["schemas"]["DeveloperSummary"];
            /** Format: date-time */
            readonly event_time: string;
            /** @description Reader-generated id; a retried request with the same id is not stored twice. */
            readonly client_event_id: string;
        };
        /**
         * @description * `RFID` - RFID scan
         *     * `MANUAL` - Manual correction
         * @enum {string}
         */
        SourceEnum: "RFID" | "MANUAL";
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly is_active: boolean;
            readonly roles: string[];
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
        };
        UserCreateRequest: {
            /** Format: email */
            email: string;
            full_name?: string;
            password: string;
        };
        VoidRequest: {
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attendance_daily_list: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                department?: string;
                developer?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `PRESENT` - Present
                 *     * `INCOMPLETE` - Incomplete (missing or unpaired scan)
                 */
                status?: "INCOMPLETE" | "PRESENT";
                work_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDailyAttendanceList"];
                };
            };
        };
    };
    attendance_daily_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this daily attendance. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyAttendance"];
                };
            };
        };
    };
    attendance_daily_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyAttendance"];
                };
            };
        };
    };
    attendance_records_list: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                developer?: number;
                device?: number;
                /**
                 * @description * `IN` - In
                 *     * `OUT` - Out
                 *     * `SCAN` - Scan (direction not classified)
                 */
                event_type?: "IN" | "OUT" | "SCAN";
                is_void?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `RFID` - RFID scan
                 *     * `MANUAL` - Manual correction
                 */
                source?: "MANUAL" | "RFID";
                work_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttendanceRecordList"];
                };
            };
        };
    };
    attendance_records_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRecordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ManualRecordRequest"];
                "multipart/form-data": components["schemas"]["ManualRecordRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
        };
    };
    attendance_records_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
        };
    };
    attendance_records_void_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VoidRequest"];
                "multipart/form-data": components["schemas"]["VoidRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
        };
    };
    attendance_records_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
        };
    };
    audit_logs_list: {
        parameters: {
            query?: {
                action?: string;
                actor?: number;
                created_after?: string;
                created_before?: string;
                entity_id?: string;
                entity_type?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditLogList"];
                };
            };
        };
    };
    audit_logs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this audit log. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLog"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    developers_list: {
        parameters: {
            query?: {
                department?: string;
                has_user?: boolean;
                manager?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                started_after?: string;
                started_before?: string;
                /**
                 * @description * `ACTIVE` - Active
                 *     * `ON_LEAVE` - On leave
                 *     * `SUSPENDED` - Suspended
                 *     * `TERMINATED` - Terminated
                 */
                status?: "ACTIVE" | "ON_LEAVE" | "SUSPENDED" | "TERMINATED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeveloperList"];
                };
            };
        };
    };
    developers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeveloperRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DeveloperRequest"];
                "multipart/form-data": components["schemas"]["DeveloperRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Developer"];
                };
            };
        };
    };
    developers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this developer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Developer"];
                };
            };
        };
    };
    developers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this developer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    developers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this developer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDeveloperRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDeveloperRequest"];
                "multipart/form-data": components["schemas"]["PatchedDeveloperRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Developer"];
                };
            };
        };
    };
    developers_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyDeveloperProfile"];
                };
            };
        };
    };
    rfid_assignments_list: {
        parameters: {
            query?: {
                active?: boolean;
                card?: number;
                developer?: number;
                /**
                 * @description * `RETURNED` - Returned
                 *     * `REPLACED` - Replaced
                 *     * `DEVELOPER_LEFT` - Developer left
                 *     * `DEVELOPER_DELETED` - Developer record deleted
                 */
                end_reason?: "DEVELOPER_DELETED" | "DEVELOPER_LEFT" | "REPLACED" | "RETURNED";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRFIDCardAssignmentList"];
                };
            };
        };
    };
    rfid_assignments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCardAssignment"];
                };
            };
        };
    };
    rfid_cards_list: {
        parameters: {
            query?: {
                assigned?: boolean;
                developer?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `ACTIVE` - Active
                 *     * `BLOCKED` - Blocked
                 *     * `RETIRED` - Retired
                 */
                status?: "ACTIVE" | "BLOCKED" | "RETIRED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRFIDCardList"];
                };
            };
        };
    };
    rfid_cards_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RFIDCardRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RFIDCardRequest"];
                "multipart/form-data": components["schemas"]["RFIDCardRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRFIDCardUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRFIDCardUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedRFIDCardUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCardUpdate"];
                };
            };
        };
    };
    rfid_cards_assign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardAssignRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CardAssignRequest"];
                "multipart/form-data": components["schemas"]["CardAssignRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_block_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CardReasonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CardReasonRequest"];
                "multipart/form-data": components["schemas"]["CardReasonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_replace_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardReplaceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CardReplaceRequest"];
                "multipart/form-data": components["schemas"]["CardReplaceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_retire_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CardReasonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CardReasonRequest"];
                "multipart/form-data": components["schemas"]["CardReasonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_unassign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_cards_unblock_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID card. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CardReasonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CardReasonRequest"];
                "multipart/form-data": components["schemas"]["CardReasonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDCard"];
                };
            };
        };
    };
    rfid_devices_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description * `ATTENDANCE` - Attendance */
                purpose?: "ATTENDANCE";
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRFIDDeviceList"];
                };
            };
        };
    };
    rfid_devices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RFIDDeviceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RFIDDeviceRequest"];
                "multipart/form-data": components["schemas"]["RFIDDeviceRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDDeviceWithKey"];
                };
            };
        };
    };
    rfid_devices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID device. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDDevice"];
                };
            };
        };
    };
    rfid_devices_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID device. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRFIDDeviceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRFIDDeviceRequest"];
                "multipart/form-data": components["schemas"]["PatchedRFIDDeviceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDDevice"];
                };
            };
        };
    };
    rfid_devices_rotate_key_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID device. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDDeviceWithKey"];
                };
            };
        };
    };
    rfid_events_list: {
        parameters: {
            query?: {
                card?: number;
                developer?: number;
                device?: number;
                event_after?: string;
                event_before?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `ACCEPTED` - Accepted
                 *     * `DUPLICATE` - Duplicate (debounced)
                 *     * `UNKNOWN_CARD` - Unknown card
                 *     * `UNASSIGNED_CARD` - Card not assigned
                 *     * `BLOCKED_CARD` - Card blocked
                 *     * `RETIRED_CARD` - Card retired
                 *     * `INACTIVE_DEVELOPER` - Developer not active
                 */
                result?: "ACCEPTED" | "BLOCKED_CARD" | "DUPLICATE" | "INACTIVE_DEVELOPER" | "RETIRED_CARD" | "UNASSIGNED_CARD" | "UNKNOWN_CARD";
                /** @description A search term. */
                search?: string;
                uid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRFIDEventList"];
                };
            };
        };
    };
    rfid_events_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ScanRequest"];
                "multipart/form-data": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
        };
    };
    rfid_events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this RFID event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFIDEvent"];
                };
            };
        };
    };
    roles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
        };
    };
    roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                role?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreateRequest"];
                "multipart/form-data": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleAssignRequest"];
                "multipart/form-data": components["schemas"]["RoleAssignRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_roles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
                role_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
